// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

// Note- Parts of the test code in this file was generated by claude code then human reviewed

import "forge-std/Test.sol";
import "../src/library/BlobData.sol";

contract BlobDataTest is BlobData {
    function validateSingleTest(
        bytes32 rootHash,
        bytes calldata commitment,
        uint256 index,
        bytes32 data,
        bytes calldata proof
    ) external {
        validateSingle(rootHash, commitment, index, data, proof);
    }

    function numDepositsToMemoryLengthTest(uint256 num) external pure returns (uint256) {
        return numDepositsToMemoryLength(num);
    }

    function leafMemoryAddressTest(uint256 number, uint256 numDeposits, bool isDeposit, uint256 which)
        external
        pure
        returns (uint256)
    {
        return leafMemoryAddress(number, numDeposits, isDeposit, which);
    }

    function txMemoryAddressTest(uint256 txNumber, uint256 numDeposits) external pure returns (uint256) {
        return txMemoryAddress(txNumber, numDeposits);
    }

    function nullifierMemoryAddressTest(uint256 txNumber, uint256 numDeposits, uint256 which)
        external
        pure
        returns (uint256)
    {
        return nullifierMemoryAddress(txNumber, numDeposits, which);
    }

    function priorRootMemoryLocationTest(uint256 number, bool isDeposit, uint256 numDeposits)
        external
        pure
        returns (uint256)
    {
        return priorRootMemoryLocation(number, isDeposit, numDeposits);
    }

    function bitReversedRootTest(uint256 i) external view returns (uint256) {
        return bitReversedRoot(i);
    }

    function expTest(uint256 b, uint256 e) external pure returns (uint256) {
        return exp(b, e);
    }

    function getRoot() external view returns (uint256) {
        return ROOT;
    }

    function getBlsModulus() external pure returns (uint256) {
        return BLS_MODULUS;
    }
}

contract CounterTest is Test {
    BlobDataTest blob;

    struct TestData {
        bytes blob;
        bytes commitment;
        uint256 index;
        bytes32 claim;
        bytes32 hash;
        bytes proof;
    }

    function setUp() public {
        blob = new BlobDataTest();
    }

    function test_SingleProof() public {
        bytes memory hexString = vm.readFileBinary("./script/testVector.bin");
        TestData memory data = abi.decode(hexString, (TestData));
        bytes32[] memory blobhashes = new bytes32[](1);
        blobhashes[0] = data.hash;
        vm.blobhashes(blobhashes);

        blob.validateSingleTest(data.hash, data.commitment, data.index, data.claim, data.proof);
    }

    function test_SingleProofReverts() public {
        bytes memory hexString = vm.readFileBinary("./script/testVector.bin");
        TestData memory data = abi.decode(hexString, (TestData));
        bytes32[] memory blobhashes = new bytes32[](1);
        blobhashes[0] = data.hash;
        vm.blobhashes(blobhashes);
        vm.expectRevert();
        blob.validateSingleTest(
            data.hash & (bytes32)(uint256(2 ** 240 - 1)), data.commitment, data.index, data.claim, data.proof
        );
        vm.expectRevert();
        blob.validateSingleTest(data.hash, data.commitment, data.index + 1, data.claim, data.proof);
        vm.expectRevert();
        blob.validateSingleTest(
            data.hash, data.commitment, data.index, (bytes32)((uint256)(data.claim) + 1), data.proof
        );
    }

    // Tests for numDepositsToMemoryLength
    // Formula: (num / 3 + depositRounding) * 4 where depositRounding = (num % 3 == 0 ? 0 : 1)
    // Each group of up to 3 deposits takes 4 memory slots

    function test_NumDepositsToMemoryLength_BasicCases() public view {
        // 0 deposits = 0 memory length
        assertEq(blob.numDepositsToMemoryLengthTest(0), 0);
        // 1-3 deposits: (0 or 1 + 1) * 4 = 4
        assertEq(blob.numDepositsToMemoryLengthTest(1), 4);
        assertEq(blob.numDepositsToMemoryLengthTest(2), 4);
        assertEq(blob.numDepositsToMemoryLengthTest(3), 4);
        // 4-6 deposits: (1 or 2 groups) * 4 = 8
        assertEq(blob.numDepositsToMemoryLengthTest(6), 8);
        // 7-9 deposits: 3 groups * 4 = 12
        assertEq(blob.numDepositsToMemoryLengthTest(9), 12);
    }

    function test_NumDepositsToMemoryLength_EdgeCases() public view {
        // Partial groups round up
        assertEq(blob.numDepositsToMemoryLengthTest(4), 8); // (1 + 1) * 4
        assertEq(blob.numDepositsToMemoryLengthTest(5), 8); // (1 + 1) * 4
        assertEq(blob.numDepositsToMemoryLengthTest(7), 12); // (2 + 1) * 4
        assertEq(blob.numDepositsToMemoryLengthTest(8), 12); // (2 + 1) * 4
        // Large values
        assertEq(blob.numDepositsToMemoryLengthTest(30), 40); // (10 + 0) * 4
        assertEq(blob.numDepositsToMemoryLengthTest(99), 132); // (33 + 0) * 4
        assertEq(blob.numDepositsToMemoryLengthTest(100), 136); // (33 + 1) * 4
    }

    function testFuzz_NumDepositsToMemoryLength(uint256 num) public view {
        // Bound to reasonable values to avoid overflow
        num = bound(num, 0, 1_000_000);

        uint256 result = blob.numDepositsToMemoryLengthTest(num);

        // Verify the formula: (num / 3 + depositRounding) * 4
        uint256 depositRounding = num % 3 == 0 ? 0 : 1;
        uint256 expected = (num / 3 + depositRounding) * 4;
        assertEq(result, expected);

        // For multiples of 3, result should be exactly (num / 3) * 4
        if (num % 3 == 0) {
            assertEq(result, (num / 3) * 4);
        }
    }

    // Tests for leafMemoryAddress
    // For deposits: returns number + number/3 (skips root fields every 3 deposits)
    // For transactions: returns depositsLength + number*15 + 11 + which

    function test_LeafMemoryAddress_Deposits() public view {
        // Formula: number + number/3
        // First group (0-2)
        assertEq(blob.leafMemoryAddressTest(0, 3, true, 0), 0);
        assertEq(blob.leafMemoryAddressTest(1, 3, true, 0), 1);
        assertEq(blob.leafMemoryAddressTest(2, 3, true, 0), 2);
        // Position 3 is root, deposit 3 skips to 4
        assertEq(blob.leafMemoryAddressTest(3, 6, true, 0), 4);
        // Multiple groups
        assertEq(blob.leafMemoryAddressTest(4, 6, true, 0), 5);
        assertEq(blob.leafMemoryAddressTest(5, 6, true, 0), 6);
        assertEq(blob.leafMemoryAddressTest(6, 9, true, 0), 8);
        assertEq(blob.leafMemoryAddressTest(7, 9, true, 0), 9);
        assertEq(blob.leafMemoryAddressTest(8, 9, true, 0), 10);

        // `which` parameter should not affect deposit results
        assertEq(blob.leafMemoryAddressTest(0, 3, true, 0), blob.leafMemoryAddressTest(0, 3, true, 1));
        assertEq(blob.leafMemoryAddressTest(0, 3, true, 0), blob.leafMemoryAddressTest(0, 3, true, 2));
    }

    function test_LeafMemoryAddress_Transactions() public view {
        // Formula: depositsLength + number*15 + 11 + which

        // No deposits (depositsLength = 0)
        assertEq(blob.leafMemoryAddressTest(0, 0, false, 0), 11);
        assertEq(blob.leafMemoryAddressTest(0, 0, false, 1), 12);
        assertEq(blob.leafMemoryAddressTest(0, 0, false, 2), 13);
        assertEq(blob.leafMemoryAddressTest(1, 0, false, 0), 26);

        // With 3 deposits (depositsLength = 4)
        assertEq(blob.leafMemoryAddressTest(0, 3, false, 0), 15); // 4 + 0 + 11 + 0
        assertEq(blob.leafMemoryAddressTest(1, 3, false, 0), 30); // 4 + 15 + 11 + 0

        // With 2 deposits (depositsLength = 4, rounds up)
        assertEq(blob.leafMemoryAddressTest(0, 2, false, 0), 15); // 4 + 0 + 11 + 0

        // Large values: 6 deposits (depositsLength = 8), tx 10
        assertEq(blob.leafMemoryAddressTest(10, 6, false, 0), 169); // 8 + 150 + 11 + 0
        assertEq(blob.leafMemoryAddressTest(10, 6, false, 1), 170);
        assertEq(blob.leafMemoryAddressTest(10, 6, false, 2), 171);
    }

    function testFuzz_LeafMemoryAddress_Deposits(uint256 number) public view {
        // Bound to reasonable values
        number = bound(number, 0, 100_000);
        uint256 numDeposits = number + 1; // Ensure numDeposits > number

        uint256 result = blob.leafMemoryAddressTest(number, numDeposits, true, 0);

        // Verify the formula: number + number/3
        uint256 expected = number + number / 3;
        assertEq(result, expected);

        // Result should always be >= number
        assertGe(result, number);
    }

    function testFuzz_LeafMemoryAddress_Transactions(uint256 number, uint256 numDeposits, uint256 which) public view {
        // Bound inputs
        number = bound(number, 0, 10_000);
        numDeposits = bound(numDeposits, 0, 10_000);
        which = bound(which, 0, 2);

        uint256 result = blob.leafMemoryAddressTest(number, numDeposits, false, which);

        // Verify the formula: depositsLength + number*15 + 11 + which
        uint256 depositRounding = numDeposits % 3 == 0 ? 0 : 1;
        uint256 depositsLength = (numDeposits / 3 + depositRounding) * 4;
        uint256 expected = depositsLength + number * 15 + 11 + which;
        assertEq(result, expected);

        // Result should always be >= depositsLength + 11
        assertGe(result, depositsLength + 11);
    }

    // Tests for txMemoryAddress
    // Formula: depositsLength + (txNumber - 1) * 15
    // Note: txNumber is 1-indexed (txNumber >= 1)

    function test_TxMemoryAddress_VariousDeposits() public view {
        // No deposits (depositsLength = 0)
        assertEq(blob.txMemoryAddressTest(1, 0), 0);
        assertEq(blob.txMemoryAddressTest(2, 0), 15);
        assertEq(blob.txMemoryAddressTest(3, 0), 30);

        // 3 deposits (depositsLength = 4)
        assertEq(blob.txMemoryAddressTest(1, 3), 4);
        assertEq(blob.txMemoryAddressTest(2, 3), 19);
        assertEq(blob.txMemoryAddressTest(3, 3), 34);

        // 2 deposits (depositsLength = 4, rounds up)
        assertEq(blob.txMemoryAddressTest(1, 2), 4);
        assertEq(blob.txMemoryAddressTest(2, 2), 19);

        // 6 deposits (depositsLength = 8)
        assertEq(blob.txMemoryAddressTest(1, 6), 8);
        assertEq(blob.txMemoryAddressTest(5, 6), 68);
        assertEq(blob.txMemoryAddressTest(10, 6), 143);

        // Large: 99 deposits (depositsLength = 132)
        assertEq(blob.txMemoryAddressTest(100, 99), 1617);

        // Verify consecutive tx spacing is 15
        uint256 tx1 = blob.txMemoryAddressTest(1, 5);
        uint256 tx2 = blob.txMemoryAddressTest(2, 5);
        assertEq(tx2 - tx1, 15);
    }

    function testFuzz_TxMemoryAddress(uint256 txNumber, uint256 numDeposits) public view {
        // Bound inputs - txNumber must be >= 1 to avoid underflow
        txNumber = bound(txNumber, 1, 10_000);
        numDeposits = bound(numDeposits, 0, 10_000);

        uint256 result = blob.txMemoryAddressTest(txNumber, numDeposits);

        // Verify the formula: depositsLength + (txNumber - 1) * 15
        uint256 depositRounding = numDeposits % 3 == 0 ? 0 : 1;
        uint256 depositsLength = (numDeposits / 3 + depositRounding) * 4;
        uint256 expected = depositsLength + (txNumber - 1) * 15;
        assertEq(result, expected);

        // Result should always be >= depositsLength
        assertGe(result, depositsLength);

        // For txNumber = 1, result should equal depositsLength
        if (txNumber == 1) {
            assertEq(result, depositsLength);
        }
    }

    // Tests for nullifierMemoryAddress
    // Formula: depositsLength + txNumber * 15 + 9 + which
    // Note: txNumber is 0-indexed, which is 0 or 1

    function test_NullifierMemoryAddress_VariousDeposits() public view {
        // No deposits (depositsLength = 0)
        assertEq(blob.nullifierMemoryAddressTest(0, 0, 0), 9);
        assertEq(blob.nullifierMemoryAddressTest(0, 0, 1), 10);
        assertEq(blob.nullifierMemoryAddressTest(1, 0, 0), 24);
        assertEq(blob.nullifierMemoryAddressTest(1, 0, 1), 25);

        // 3 deposits (depositsLength = 4)
        assertEq(blob.nullifierMemoryAddressTest(0, 3, 0), 13); // 4 + 0 + 9 + 0
        assertEq(blob.nullifierMemoryAddressTest(0, 3, 1), 14);
        assertEq(blob.nullifierMemoryAddressTest(1, 3, 0), 28); // 4 + 15 + 9 + 0

        // 2 deposits (depositsLength = 4, rounds up)
        assertEq(blob.nullifierMemoryAddressTest(0, 2, 0), 13); // 4 + 0 + 9 + 0
        assertEq(blob.nullifierMemoryAddressTest(0, 2, 1), 14);

        // 6 deposits (depositsLength = 8)
        assertEq(blob.nullifierMemoryAddressTest(0, 6, 0), 17); // 8 + 0 + 9 + 0
        assertEq(blob.nullifierMemoryAddressTest(5, 6, 0), 92); // 8 + 75 + 9 + 0

        // Large: 99 deposits (depositsLength = 132)
        assertEq(blob.nullifierMemoryAddressTest(100, 99, 0), 1641); // 132 + 1500 + 9 + 0
        assertEq(blob.nullifierMemoryAddressTest(100, 99, 1), 1642);

        // Verify spacing: consecutive tx nullifiers are 15 apart
        uint256 tx0 = blob.nullifierMemoryAddressTest(0, 5, 0);
        uint256 tx1 = blob.nullifierMemoryAddressTest(1, 5, 0);
        assertEq(tx1 - tx0, 15);

        // Verify nullifier pair spacing is 1
        uint256 null0 = blob.nullifierMemoryAddressTest(0, 4, 0);
        uint256 null1 = blob.nullifierMemoryAddressTest(0, 4, 1);
        assertEq(null1 - null0, 1);
    }

    function testFuzz_NullifierMemoryAddress(uint256 txNumber, uint256 numDeposits, uint256 which) public view {
        // Bound inputs
        txNumber = bound(txNumber, 0, 10_000);
        numDeposits = bound(numDeposits, 0, 10_000);
        which = bound(which, 0, 1);

        uint256 result = blob.nullifierMemoryAddressTest(txNumber, numDeposits, which);

        // Verify the formula: depositsLength + txNumber * 15 + 9 + which
        uint256 depositRounding = numDeposits % 3 == 0 ? 0 : 1;
        uint256 depositsLength = (numDeposits / 3 + depositRounding) * 4;
        uint256 expected = depositsLength + txNumber * 15 + 9 + which;
        assertEq(result, expected);

        // Result should always be >= depositsLength + 9
        assertGe(result, depositsLength + 9);
    }

    // Tests for priorRootMemoryLocation
    // For deposits: number * 4 - 1 (number >= 1, number <= numDeposits / 3)
    // For transactions: depositsLength + number * 15 - 1 (number >= 1)

    function test_PriorRootMemoryLocation_Deposits() public view {
        // Formula: number * 4 - 1
        // Group 1: 1 * 4 - 1 = 3
        assertEq(blob.priorRootMemoryLocationTest(1, true, 3), 3);
        assertEq(blob.priorRootMemoryLocationTest(1, true, 6), 3);
        assertEq(blob.priorRootMemoryLocationTest(1, true, 9), 3);
        // Group 2: 2 * 4 - 1 = 7
        assertEq(blob.priorRootMemoryLocationTest(2, true, 6), 7);
        assertEq(blob.priorRootMemoryLocationTest(2, true, 9), 7);
        // Group 3: 3 * 4 - 1 = 11
        assertEq(blob.priorRootMemoryLocationTest(3, true, 9), 11);
        // Group 4: 4 * 4 - 1 = 15
        assertEq(blob.priorRootMemoryLocationTest(4, true, 12), 15);

        // Verify consecutive groups are spaced 4 apart
        uint256 root1 = blob.priorRootMemoryLocationTest(1, true, 9);
        uint256 root2 = blob.priorRootMemoryLocationTest(2, true, 9);
        assertEq(root2 - root1, 4);
    }

    function test_PriorRootMemoryLocation_Transactions() public view {
        // Formula: depositsLength + number * 15 - 1

        // No deposits (depositsLength = 0)
        assertEq(blob.priorRootMemoryLocationTest(1, false, 0), 14);
        assertEq(blob.priorRootMemoryLocationTest(2, false, 0), 29);
        assertEq(blob.priorRootMemoryLocationTest(3, false, 0), 44);

        // 3 deposits (depositsLength = 4)
        assertEq(blob.priorRootMemoryLocationTest(1, false, 3), 18); // 4 + 15 - 1
        assertEq(blob.priorRootMemoryLocationTest(2, false, 3), 33); // 4 + 30 - 1

        // 2 deposits (depositsLength = 4, rounds up)
        assertEq(blob.priorRootMemoryLocationTest(1, false, 2), 18); // 4 + 15 - 1
        assertEq(blob.priorRootMemoryLocationTest(2, false, 2), 33); // 4 + 30 - 1

        // Large: 99 deposits (depositsLength = 132)
        assertEq(blob.priorRootMemoryLocationTest(100, false, 99), 1631); // 132 + 1500 - 1

        // Verify consecutive tx roots are spaced 15 apart
        uint256 root1 = blob.priorRootMemoryLocationTest(1, false, 6);
        uint256 root2 = blob.priorRootMemoryLocationTest(2, false, 6);
        assertEq(root2 - root1, 15);
    }

    function testFuzz_PriorRootMemoryLocation_Deposits(uint256 number, uint256 numDeposits) public view {
        // Bound inputs - number must be >= 1 and <= numDeposits / 3
        numDeposits = bound(numDeposits, 3, 30_000);
        number = bound(number, 1, numDeposits / 3);

        uint256 result = blob.priorRootMemoryLocationTest(number, true, numDeposits);

        // Verify the formula: number * 4 - 1
        uint256 expected = number * 4 - 1;
        assertEq(result, expected);
    }

    function testFuzz_PriorRootMemoryLocation_Transactions(uint256 number, uint256 numDeposits) public view {
        // Bound inputs - number must be >= 1
        number = bound(number, 1, 10_000);
        numDeposits = bound(numDeposits, 0, 10_000);

        uint256 result = blob.priorRootMemoryLocationTest(number, false, numDeposits);

        // Verify the formula: depositsLength + number * 15 - 1
        uint256 depositRounding = numDeposits % 3 == 0 ? 0 : 1;
        uint256 depositsLength = (numDeposits / 3 + depositRounding) * 4;
        uint256 expected = depositsLength + number * 15 - 1;
        assertEq(result, expected);
    }

    // Tests for bitReversedRoot
    // The function computes ROOT^(bitReverse12(i)) where ROOT is a primitive 4096th root of unity
    // Bit reversal treats i as a 12-bit number (i < 4096)

    function test_BitReversedRoot_SmallIndices() public view {
        uint256 root = blob.getRoot();

        // i=0: bit reverse of 0 is 0, ROOT^0 = 1
        assertEq(blob.bitReversedRootTest(0), 1);

        // i=1: reversed is 2048, result = ROOT^2048
        assertEq(blob.bitReversedRootTest(1), blob.expTest(root, 2048));

        // i=2: reversed is 1024, result = ROOT^1024
        assertEq(blob.bitReversedRootTest(2), blob.expTest(root, 1024));

        // i=3: reversed is 3072
        assertEq(blob.bitReversedRootTest(3), blob.expTest(root, 3072));
    }

    function test_BitReversedRoot_PowerOfTwoAndSymmetry() public view {
        uint256 root = blob.getRoot();

        // Powers of two
        assertEq(blob.bitReversedRootTest(4), blob.expTest(root, 512));
        assertEq(blob.bitReversedRootTest(8), blob.expTest(root, 256));
        assertEq(blob.bitReversedRootTest(2048), blob.expTest(root, 1));
        assertEq(blob.bitReversedRootTest(2048), root); // ROOT^1 = ROOT

        // Max index: 4095 reversed is 4095
        assertEq(blob.bitReversedRootTest(4095), blob.expTest(root, 4095));

        // Symmetric: i=1 and i=2048 are bit-reversed pairs
        assertEq(blob.bitReversedRootTest(1), blob.expTest(root, 2048));
        assertEq(blob.bitReversedRootTest(2048), blob.expTest(root, 1));
    }

    function test_BitReversedRoot_RootProperties() public view {
        uint256 root = blob.getRoot();
        uint256 blsModulus = blob.getBlsModulus();

        // ROOT^4096 should equal 1 (primitive 4096th root)
        assertEq(blob.expTest(root, 4096), 1);

        // ROOT should not be 1
        assertTrue(root != 1);

        // ROOT should be less than BLS_MODULUS
        assertLt(root, blsModulus);

        // ROOT^2048 should be -1 mod p (since ROOT^4096 = 1)
        uint256 root2048 = blob.expTest(root, 2048);
        assertTrue(root2048 == 1 || root2048 == blsModulus - 1);
    }

    function test_BitReversedRoot_AllResultsValid() public view {
        uint256 blsModulus = blob.getBlsModulus();
        // All results should be non-zero and less than BLS_MODULUS
        for (uint256 i = 0; i < 16; i++) {
            uint256 result = blob.bitReversedRootTest(i);
            assertTrue(result != 0);
            assertLt(result, blsModulus);
        }
    }

    function testFuzz_BitReversedRoot_ConsistentFormula(uint256 i) public view {
        // Bound i to valid range
        i = bound(i, 0, 4095);

        uint256 result = blob.bitReversedRootTest(i);
        uint256 root = blob.getRoot();

        // Compute bit reversal manually for 12 bits
        uint256 reversed = 0;
        uint256 temp = i;
        for (uint256 bit = 0; bit < 12; bit++) {
            reversed = (reversed << 1) | (temp & 1);
            temp = temp >> 1;
        }

        // Verify result equals ROOT^reversed
        uint256 expected = blob.expTest(root, reversed);
        assertEq(result, expected);
    }
}
