// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

// Note- Parts of the test code in this file was generated by ai then human reviewed

import "forge-std/Test.sol";
import "../src/NullifierChallenge.sol";
import "../src/Spine.sol";
import "./mocks/FakeBlobs.sol";

contract NullifierChallengeHarness is NullifierChallenge, FakeBlobs {
    function setupBlocks(BlockData memory data, uint256 seed) public returns (BlockData memory, bytes32[] memory ret) {
        uint256 depositSize = data.numDeposits % 3 == 0 ? (data.numDeposits / 3) * 4 : (data.numDeposits / 3 + 1) * 4;
        uint256 dataNeeded = depositSize + data.numTransactions * 15;
        bytes32[] memory randomData = new bytes32[](dataNeeded);
        for (uint256 i = 0; i < dataNeeded; i++) {
            randomData[i] = keccak256(abi.encodePacked(i, seed));
        }
        ret = store(randomData);
        data.blobhashes = ret;
        return (data, ret);
    }

    function addBlockTest(BlockData memory data, uint256[] memory indices) public returns (BlockData memory) {
        addBlock(data, indices);
        return (data);
    }

    function validateSingle(bytes32 rootHash, bytes calldata, uint256 index, bytes32 data, bytes calldata)
        internal
        view
        override
    {
        require(access(rootHash, index) == data);
    }

    // Expose sequencer status for testing
    function getSequencerStatus(address sequencer)
        public
        view
        returns (
            bool isActive,
            bool isPriority,
            uint8 priorityIndex,
            uint64 blocknumberChallenged,
            uint64 timestampChallenged,
            uint64 stakeAmount,
            address payable challenger
        )
    {
        SequencerStatus memory status = sequencers[sequencer];
        return (
            status.isActive,
            status.isPriority,
            status.priorityIndex,
            status.blocknumberChallenged,
            status.timestampChallenged,
            status.stakeAmount,
            status.challenger
        );
    }

    // Expose current block number
    function getBlockCount() public view returns (uint256) {
        return getCurrentBlocknumber();
    }

    // Helper to fund a sequencer - forwards the call with value
    receive() external payable {}

    function fundSequencer() public payable {
        // Directly update sequencer state since fund() requires msg.sender to be the sequencer
        sequencers[msg.sender].isActive = true;
        sequencers[msg.sender].stakeAmount += uint64(msg.value / (10 ** 14));
    }

    // Helper to compute nullifier memory address
    function getNullifierMemoryAddress(uint256 txNr, uint256 numDeposits, uint256 which) public pure returns (uint256) {
        return nullifierMemoryAddress(txNr, numDeposits, which);
    }

    // Helper to set a value at a logical index in blob storage
    // Handles bit reversal internally so caller uses logical indices
    function setValueAt(bytes32 blobHash, uint256 logicalIndex, bytes32 value) public {
        uint256 storageIndex = bitReverse(logicalIndex);
        storeAt(blobHash, storageIndex, value);
    }

}

contract NullifierChallengeTest is Test {
    NullifierChallengeHarness harness;

    function setUp() public {
        harness = new NullifierChallengeHarness();
    }

    // ==================== ORDERING VALIDATION TESTS ====================

    // Test that nullifier reuse within same block can be challenged
    // Note: txNr ordering within same block is not enforced because:
    // 1. Two challengers cannot submit in the same transaction
    // 2. Cannot challenge post rollback
    // So the "first/second" naming is just for the challenger's convenience
    function test_SameBlockNullifierReuse() public {
        bytes32 sharedNullifier = keccak256("shared_nullifier");
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        // Create a block with 2 transactions, both having the same nullifier
        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 2,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        // Setup with shared nullifier at tx 0 and tx 1
        uint256 dataNeeded = 2 * 15; // 2 transactions, 15 fields each
        bytes32[] memory randomData = new bytes32[](dataNeeded);
        for (uint256 i = 0; i < dataNeeded; i++) {
            randomData[i] = keccak256(abi.encodePacked(i, uint256(123)));
        }
        // Set same nullifier at tx 0 position 9 and tx 1 position 24
        randomData[9] = sharedNullifier; // tx 0, nullifier 0
        randomData[24] = sharedNullifier; // tx 1, nullifier 0 (15 + 9)

        bytes32[] memory ret = harness.store(randomData);
        block1.blobhashes = ret;
        vm.blobhashes(ret);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);

        // Challenge with loaders pointing to different txs in same block
        NullifierChallenge.NullifierLoader memory loader1 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});
        NullifierChallenge.NullifierLoader memory loader2 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 1, whichNullifier: 0, commitment: "", proof: ""});

        Spine.BlockData memory emptyBlock;
        // This should succeed - nullifier reuse in same block is a valid challenge
        harness.challengeNullifier(sharedNullifier, loader1, loader2, emptyBlock);
    }

    // ==================== ORDERING VALIDATION TESTS (continued) ====================

    // Test that challenges with blocks in wrong order are rejected
    // The "first" block must have blockNr <= "second" block
    function test_RejectFirstBlockAfterSecond() public {
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        (block1, blobhashes) = harness.setupBlocks(block1, 0);
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;

        // Add two blocks with same data
        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        bytes32 nullifier = harness.access(blobhashes[0], 9);

        // Create loaders with WRONG ORDER - first has higher blockNr than second
        NullifierChallenge.NullifierLoader memory loader1 = NullifierChallenge.NullifierLoader({
            data: block2, // blockNr = 1 (higher)
            txNr: 0,
            whichNullifier: 0,
            commitment: "",
            proof: ""
        });
        NullifierChallenge.NullifierLoader memory loader2 = NullifierChallenge.NullifierLoader({
            data: block1, // blockNr = 0 (lower)
            txNr: 0,
            whichNullifier: 0,
            commitment: "",
            proof: ""
        });

        Spine.BlockData memory emptyBlock;

        // Should revert - first.blockNr (1) > second.blockNr (0)
        vm.expectRevert();
        harness.challengeNullifier(nullifier, loader1, loader2, emptyBlock);
    }

    // ==================== BOUNDARY TESTS ====================

    // Test that txNr out of bounds is properly rejected
    // txNr is 0-indexed, so with numTransactions=1, only txNr=0 is valid
    function test_TxNrOutOfBoundsRejected() public {
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1, // Only 1 tx, valid indices are [0]
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        (block1, blobhashes) = harness.setupBlocks(block1, 0);
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        // Create loader with txNr = 1, but numTransactions = 1
        // Valid txNr should be 0 only (0-indexed), so txNr=1 is out of bounds
        NullifierChallenge.NullifierLoader memory loader1 = NullifierChallenge.NullifierLoader({
            data: block1,
            txNr: 1, // OUT OF BOUNDS - should be rejected
            whichNullifier: 0,
            commitment: "",
            proof: ""
        });
        NullifierChallenge.NullifierLoader memory loader2 = NullifierChallenge.NullifierLoader({
            data: block2,
            txNr: 1, // OUT OF BOUNDS - should be rejected
            whichNullifier: 0,
            commitment: "",
            proof: ""
        });

        // Accessing nullifier at position beyond transaction data
        bytes32 outOfBoundsData = harness.access(blobhashes[0], 24); // 15 + 9

        // Should revert due to bounds checking
        vm.expectRevert();
        harness.challengeNullifier(outOfBoundsData, loader1, loader2, block1);
    }

    // ==================== SLASHING MECHANISM TESTS ====================

    // Test that slashing correctly sets the challenger address
    // (Previously bugged: used == instead of = for assignments)
    function test_SlashingSetsChallenger() public {
        address sequencer = address(0x1234);
        address challenger = address(this);

        // Fund the sequencer so they have stake
        vm.deal(sequencer, 100 ether);
        vm.prank(sequencer);
        harness.fundSequencer{value: 20 ether}();

        // Verify sequencer is active
        (bool isActive,,,,,, address payable currentChallenger) = harness.getSequencerStatus(sequencer);
        assertTrue(isActive, "Sequencer should be active");
        assertEq(currentChallenger, address(0), "No challenger initially");

        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: sequencer, // Assign to funded sequencer
            blobhashes: blobhashes
        });

        (block1, blobhashes) = harness.setupBlocks(block1, 0);
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        bytes32 nullifier = harness.access(blobhashes[0], 9);

        NullifierChallenge.NullifierLoader memory loader1 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});
        NullifierChallenge.NullifierLoader memory loader2 =
            NullifierChallenge.NullifierLoader({data: block2, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});

        // Challenge as the challenger address
        vm.prank(challenger);
        harness.challengeNullifier(nullifier, loader1, loader2, block1);

        // Verify sequencer was deactivated
        (isActive,,,,,, currentChallenger) = harness.getSequencerStatus(sequencer);
        assertFalse(isActive, "Sequencer should be slashed/inactive");

        // The challenger should be set to msg.sender
        assertEq(currentChallenger, challenger, "Challenger should be set to msg.sender");
    }

    // ==================== SAME TRANSACTION TESTS ====================

    // Test that same tx, same nullifier index should be rejected
    function test_RejectSameExactNullifierLocation() public {
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        (block1, blobhashes) = harness.setupBlocks(block1, 0);
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);

        bytes32 nullifier = harness.access(blobhashes[0], 9);

        // Both loaders point to exact same location
        NullifierChallenge.NullifierLoader memory loader1 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});
        NullifierChallenge.NullifierLoader memory loader2 = NullifierChallenge.NullifierLoader({
            data: block1,
            txNr: 0,
            whichNullifier: 0, // Same position
            commitment: "",
            proof: ""
        });

        Spine.BlockData memory emptyBlock;

        // Should revert - cannot prove reuse against same exact location
        vm.expectRevert();
        harness.challengeNullifier(nullifier, loader1, loader2, emptyBlock);
    }

    // ==================== DEPOSIT OFFSET TESTS ====================

    // Test nullifier memory calculation with deposits present (both round and non-round counts)
    function test_NullifierWithDeposits() public {
        // Test 1: 3 deposits (round) = 4 memory slots, nullifier at position 13
        uint256 expectedPos3 = harness.getNullifierMemoryAddress(0, 3, 0);
        assertEq(expectedPos3, 13, "3 deposits: nullifier position should be 13");

        // Test 2: 4 deposits (non-round, triggers rounding) = 8 memory slots, nullifier at position 17
        uint256 expectedPos4 = harness.getNullifierMemoryAddress(0, 4, 0);
        assertEq(expectedPos4, 17, "4 deposits: nullifier position should be 17");

        // Now verify with actual challenge using 4 deposits (the more complex case)
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 4,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        uint256 dataNeeded = 8 + 15; // 8 for deposits, 15 for tx
        bytes32[] memory randomData = new bytes32[](dataNeeded);
        for (uint256 i = 0; i < dataNeeded; i++) {
            randomData[i] = keccak256(abi.encodePacked(i, uint256(999)));
        }

        bytes32[] memory ret = harness.store(randomData);
        block1.blobhashes = ret;
        vm.blobhashes(ret);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        bytes32 nullifier = harness.access(ret[0], expectedPos4);

        NullifierChallenge.NullifierLoader memory loader1 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});
        NullifierChallenge.NullifierLoader memory loader2 =
            NullifierChallenge.NullifierLoader({data: block2, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});

        harness.challengeNullifier(nullifier, loader1, loader2, block1);
    }

    // ==================== INVALID INPUT TESTS ====================

    // Test with invalid whichNullifier (>1)
    function test_InvalidWhichNullifier() public {
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        (block1, blobhashes) = harness.setupBlocks(block1, 0);
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        NullifierChallenge.NullifierLoader memory loader1 = NullifierChallenge.NullifierLoader({
            data: block1,
            txNr: 0,
            whichNullifier: 2, // INVALID - only 0 and 1 are valid
            commitment: "",
            proof: ""
        });
        NullifierChallenge.NullifierLoader memory loader2 =
            NullifierChallenge.NullifierLoader({data: block2, txNr: 0, whichNullifier: 2, commitment: "", proof: ""});

        bytes32 arbitraryNullifier = keccak256("arbitrary");

        // Should revert due to assert in nullifierMemoryAddress
        vm.expectRevert();
        harness.challengeNullifier(arbitraryNullifier, loader1, loader2, block1);
    }

    // Test with non-included block (wrong blockNr)
    function test_NonIncludedBlockRejected() public {
        bytes32 anchor = keccak256("anchor");
        bytes32[] memory blobhashes = new bytes32[](1);

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        (block1, blobhashes) = harness.setupBlocks(block1, 0);
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        block1 = harness.addBlockTest(block1, indices);

        // Create fake block that was never added
        Spine.BlockData memory fakeBlock = Spine.BlockData({
            anchor: keccak256("fake"),
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: 999, // Non-existent block number
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: blobhashes
        });

        NullifierChallenge.NullifierLoader memory loader1 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});
        NullifierChallenge.NullifierLoader memory loader2 = NullifierChallenge.NullifierLoader({
            data: fakeBlock, // Non-included block
            txNr: 0,
            whichNullifier: 0,
            commitment: "",
            proof: ""
        });

        bytes32 nullifier = harness.access(blobhashes[0], 9);

        // Should revert due to isBlockIncluded check
        vm.expectRevert();
        harness.challengeNullifier(nullifier, loader1, loader2, block1);
    }

    // ==================== MULTI-BLOB TESTS ====================

    // Test challenge with data spanning multiple blobs (both first and second blob access)
    function test_MultipleBlobsNullifierChallenge() public {
        bytes32 anchor = keccak256("anchor");

        // Create block large enough to span multiple blobs
        // Each blob holds 4096 elements, each tx needs 15
        // 300 transactions = 4500 elements = 2 blobs
        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 300,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](2)
        });

        (block1,) = harness.setupBlocks(block1, 111);

        bytes32[] memory blobhashes = block1.blobhashes;
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](2);
        indices[0] = 0;
        indices[1] = 1;

        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        // Test 1: Access nullifier in first blob (tx 0, position 9)
        bytes32 nullifier = harness.access(blobhashes[0], 9);

        NullifierChallenge.NullifierLoader memory loader1 =
            NullifierChallenge.NullifierLoader({data: block1, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});
        NullifierChallenge.NullifierLoader memory loader2 =
            NullifierChallenge.NullifierLoader({data: block2, txNr: 0, whichNullifier: 0, commitment: "", proof: ""});

        harness.challengeNullifier(nullifier, loader1, loader2, block1);

        // Test 2: Access nullifier in second blob (tx 280)
        // tx 280's nullifier 0: 280*15 + 9 = 4209, blob 1 position 4209 % 4096 = 113
        // Need to add blocks again after rollback
        block1.blockNr = 0;
        block1 = harness.addBlockTest(block1, indices);
        block2 = harness.addBlockTest(block1, indices);

        uint256 expectedPos = harness.getNullifierMemoryAddress(280, 0, 0);
        uint256 blobIndex = expectedPos / 4096;
        uint256 posInBlob = expectedPos % 4096;
        assertEq(blobIndex, 1, "Should be in second blob");

        nullifier = harness.access(blobhashes[blobIndex], posInBlob);

        loader1.data = block1;
        loader1.txNr = 280;
        loader2.data = block2;
        loader2.txNr = 280;

        harness.challengeNullifier(nullifier, loader1, loader2, block1);
    }

    // ==================== FUZZ TESTS ====================

    // Helper to calculate deposit memory size
    function _depositMemorySize(uint256 numDeposits) internal pure returns (uint256) {
        if (numDeposits == 0) return 0;
        return numDeposits % 3 == 0 ? (numDeposits / 3) * 4 : (numDeposits / 3 + 1) * 4;
    }

    // Helper to calculate number of blobs needed
    function _numBlobsNeeded(uint256 numDeposits, uint256 numTransactions) internal pure returns (uint256) {
        uint256 totalElements = _depositMemorySize(numDeposits) + numTransactions * 15;
        return (totalElements + 4095) / 4096; // Ceiling division
    }

    // Helper to create and add an intermediate block with unique random data
    // Separated into its own function to reduce stack pressure in the main fuzz test
    function _addIntermediateBlock(uint256 seed) internal returns (Spine.BlockData memory) {
        Spine.BlockData memory intermediateBlock = Spine.BlockData({
            anchor: keccak256(abi.encodePacked("intermediate", seed)),
            timestamp: block.timestamp,
            numTransactions: 100,
            numDeposits: 250,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](1)
        });
        (intermediateBlock,) = harness.setupBlocks(intermediateBlock, seed);
        vm.blobhashes(intermediateBlock.blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;

        return harness.addBlockTest(intermediateBlock, indices);
    }

    /// @notice Fuzz test for valid nullifier challenges with random block configurations
    /// @param seed Random seed for data generation
    /// @param numDeposits Number of deposits (bounded to reasonable range)
    /// @param numTransactions Number of transactions (bounded to ensure <= 6 blobs)
    /// @param txNrFirst Transaction number to challenge in first block
    /// @param whichNullifier1 Which nullifier (0 or 1) for first loader
    /// @param whichNullifier2 Which nullifier (0 or 1) for second loader
    /// @param numIntermediateBlocks Number of blocks between the two challenged blocks
    function testFuzz_ValidNullifierChallenge(
        uint256 seed,
        uint16 numDeposits,
        uint16 numTransactions,
        uint16 txNrFirst,
        uint8 whichNullifier1,
        uint8 whichNullifier2,
        uint8 numIntermediateBlocks
    ) public {
        vm.pauseGasMetering();
        // Target up to 6 blobs = 24576 elements max (keeps gas/memory manageable)
        // Each tx = 15 elements, so max ~1600 tx with no deposits
        // Cap deposits to leave room for transactions
        uint256 boundedDeposits = bound(numDeposits, 0, 2000); // ~2668 slots max

        // Calculate remaining capacity for transactions
        uint256 depositSlots = _depositMemorySize(boundedDeposits);
        uint256 maxElements = 6 * 4096; // 6 blobs max for gas efficiency
        uint256 remainingSlots = depositSlots >= maxElements ? 15 : maxElements - depositSlots;
        uint256 maxTx = remainingSlots / 15;
        if (maxTx == 0) maxTx = 1;

        uint256 boundedTransactions = bound(numTransactions, 1, maxTx);
        uint256 boundedTxNr = bound(txNrFirst, 0, boundedTransactions - 1);
        uint256 boundedWhich1 = bound(whichNullifier1, 0, 1);
        uint256 boundedWhich2 = bound(whichNullifier2, 0, 1);
        uint256 boundedIntermediateBlocks = bound(numIntermediateBlocks, 0, 10);

        bytes32 anchor = keccak256(abi.encodePacked("anchor", seed));

        // Create initial block - blobhashes will be set by setupBlocks
        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: boundedTransactions,
            numDeposits: boundedDeposits,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](1) // Placeholder, will be replaced
        });

        // For valid challenge, we need the nullifier VALUES to match
        (block1,) = harness.setupBlocks(block1, seed);
        bytes32[] memory blobhashes = block1.blobhashes;

        // Use actual blob count from store() result
        uint256 numBlobs = blobhashes.length;
        vm.blobhashes(blobhashes);

        // Create blob indices array using actual blob count
        uint256[] memory indices = new uint256[](numBlobs);
        for (uint256 i = 0; i < numBlobs; i++) {
            indices[i] = i;
        }

        // Add first block
        block1 = harness.addBlockTest(block1, indices);

        // Track the block that comes right before block2 (for rollback target)
        Spine.BlockData memory rollbackTarget = block1;

        // Add intermediate blocks with unique random data
        for (uint256 i = 0; i < boundedIntermediateBlocks; i++) {
            vm.warp(block.timestamp + 1);
            // Each intermediate block gets unique data via different seed
            rollbackTarget = _addIntermediateBlock(seed);
        }

        // Add time gap before final block
        vm.warp(block.timestamp + 1);

        // Restore block1's blobhashes for the final block (to create duplicate nullifiers)
        vm.blobhashes(blobhashes);

        // Add second block with same blob data as block1 (creates duplicate nullifiers)
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        // Calculate nullifier position using first loader's index
        uint256 nullifierPos = harness.getNullifierMemoryAddress(boundedTxNr, boundedDeposits, boundedWhich1);
        uint256 blobIndex = nullifierPos / 4096;
        uint256 posInBlob = nullifierPos % 4096;

        bytes32 nullifier = harness.access(blobhashes[blobIndex], posInBlob);

        if (boundedWhich1 != boundedWhich2) {
            uint256 absoluteAddress = harness.getNullifierMemoryAddress(boundedTxNr, boundedDeposits, boundedWhich2);
            harness.setValueAt(block2.blobhashes[absoluteAddress / 4096], absoluteAddress % 4096, nullifier);
        }

        NullifierChallenge.NullifierLoader memory loader1 = NullifierChallenge.NullifierLoader({
            data: block1, txNr: boundedTxNr, whichNullifier: boundedWhich1, commitment: "", proof: ""
        });
        NullifierChallenge.NullifierLoader memory loader2 = NullifierChallenge.NullifierLoader({
            data: block2, txNr: boundedTxNr, whichNullifier: boundedWhich2, commitment: "", proof: ""
        });

        // Challenge should succeed - same nullifier in two blocks
        // Use rollbackTarget (the block immediately before block2) for correct rollback
        harness.challengeNullifier(nullifier, loader1, loader2, rollbackTarget);

        // Verify rollback occurred
        // After rollback: block1 (0) + intermediate blocks (1 to n) remain, block2 is removed
        // rollback(block2.blockNr) sets roots.length = block2.blockNr = 1 + boundedIntermediateBlocks
        assertEq(
            harness.getBlockCount(), 1 + boundedIntermediateBlocks, "Should have rolled back to correct block count"
        );
    }

    /// @notice Fuzz test that wrong nullifier values are rejected
    /// @param seed Random seed
    /// @param numTransactions Number of transactions
    /// @param whichNullifier1 Which nullifier (0 or 1) for first loader
    /// @param whichNullifier2 Which nullifier (0 or 1) for second loader
    /// @param fakeNullifierSeed Seed for generating fake nullifier
    function testFuzz_WrongNullifierRejected(
        uint256 seed,
        uint8 numTransactions,
        uint8 whichNullifier1,
        uint8 whichNullifier2,
        uint256 fakeNullifierSeed
    ) public {
        uint256 boundedTx = bound(numTransactions, 1, 100);
        uint256 boundedWhich1 = bound(whichNullifier1, 0, 1);
        uint256 boundedWhich2 = bound(whichNullifier2, 0, 1);

        bytes32 anchor = keccak256(abi.encodePacked("anchor", seed));

        Spine.BlockData memory block1 = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: boundedTx,
            numDeposits: 0,
            blockNr: 0,
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](1)
        });

        (block1,) = harness.setupBlocks(block1, seed);
        bytes32[] memory blobhashes = block1.blobhashes;
        vm.blobhashes(blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;

        block1 = harness.addBlockTest(block1, indices);
        Spine.BlockData memory block2 = harness.addBlockTest(block1, indices);

        // Generate a fake nullifier that won't match actual data
        bytes32 fakeNullifier = keccak256(abi.encodePacked("fake", fakeNullifierSeed));

        NullifierChallenge.NullifierLoader memory loader1 = NullifierChallenge.NullifierLoader({
            data: block1, txNr: 0, whichNullifier: boundedWhich1, commitment: "", proof: ""
        });
        NullifierChallenge.NullifierLoader memory loader2 = NullifierChallenge.NullifierLoader({
            data: block2, txNr: 0, whichNullifier: boundedWhich2, commitment: "", proof: ""
        });

        // Should revert - fake nullifier doesn't match blob data at either position
        vm.expectRevert();
        harness.challengeNullifier(fakeNullifier, loader1, loader2, block1);
    }
}
