// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

// Note- Parts of the test code in this file was generated by ai then human reviewed

import "forge-std/Test.sol";
import "../src/SequencerRegistry.sol";
import "../src/Spine.sol";
import "../src/TransactionRegistry.sol";
import "./mocks/MockYieldRouter.sol";
import "./mocks/MockTransactionRegistry.sol";
import "./mocks/FakeZk.sol";

// Harness to expose internal functions and state
contract SequencerRegistryHarness is SequencerRegistry {
    constructor(
        bytes32 genesis,
        IYieldRouter _yieldRouter,
        IUpdateVerifier _predictableUpdateVerifier,
        ITransferVerifier _transactionZkVerifier,
        ITransactionRegistry _transferRegistry
    ) {
        GENESIS_ANCHOR = genesis;
        yieldRouter = _yieldRouter;
        predictableUpdateVerifier = _predictableUpdateVerifier;
        transactionZkVerifier = _transactionZkVerifier;
        transferRegistry = _transferRegistry;
        _initializeOwner(msg.sender);
    }

    function slashSequencer(address sequencer, uint256 blockNumber) external {
        slash(sequencer, blockNumber);
    }

    function getSequencerStatus(address who)
        external
        view
        returns (
            bool isActive,
            bool isPriority,
            uint8 priorityIndex,
            uint64 blocknumberChallenged,
            uint64 timestampChallenged,
            uint64 stakeAmount,
            address payable challenger
        )
    {
        SequencerStatus memory s = sequencers[who];
        return (
            s.isActive,
            s.isPriority,
            s.priorityIndex,
            s.blocknumberChallenged,
            s.timestampChallenged,
            s.stakeAmount,
            s.challenger
        );
    }

    function getFirstLookSequencersLength() external view returns (uint256) {
        return firstLookSequencers.length;
    }

    function getFirstLookSequencer(uint256 index) external view returns (address) {
        return firstLookSequencers[index];
    }

    receive() external payable {}
}

// Helper contract that rejects ETH transfers
contract RejectingContract {
    // No receive or fallback, so it will reject ETH transfers

    }

contract SequencerRegistryTest is Test {
    SequencerRegistryHarness harness;
    MockYieldRouter yieldRouter;
    FakeZK fakeZk;
    MockTransactionRegistry txRegistry;

    uint256 constant EPOCH_LENGTH = 10;
    uint256 constant CHALLENGE_WINDOW = 10;

    address owner = address(this);
    address sequencer1 = address(0x1001);
    address sequencer2 = address(0x1002);
    address sequencer3 = address(0x1003);
    address challenger = address(0x2001);

    function setUp() public {
        yieldRouter = new MockYieldRouter();
        fakeZk = new FakeZK();
        txRegistry = new MockTransactionRegistry();

        harness = new SequencerRegistryHarness(keccak256("genesis"), yieldRouter, fakeZk, fakeZk, txRegistry);

        vm.deal(sequencer1, 1000 ether);
        vm.deal(sequencer2, 1000 ether);
        vm.deal(sequencer3, 1000 ether);
        vm.deal(challenger, 100 ether);
        vm.deal(address(harness), 1000 ether);
    }

    // ==================== FUND TESTS ====================

    function test_FundBasic() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        (bool isActive,,,,, uint64 stakeAmount,) = harness.getSequencerStatus(sequencer1);
        assertTrue(isActive, "Sequencer should be active");
        assertEq(stakeAmount, 200000, "Stake amount should be 200,000 units");
    }

    function test_FundBlockedAfterSlash() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        vm.prank(challenger);
        harness.slashSequencer(sequencer1, 0);

        vm.prank(sequencer1);
        vm.expectRevert();
        harness.fund{value: 20 ether}();
    }

    // ==================== PRIORITY SEQUENCER TESTS ====================

    function test_AddFirstLookSetsPriorityIndex() public {
        // Add three sequencers and verify indices
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        vm.prank(sequencer2);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer2);

        vm.prank(sequencer3);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer3);

        (, bool isPriority1, uint8 idx1,,,,) = harness.getSequencerStatus(sequencer1);
        (, bool isPriority2, uint8 idx2,,,,) = harness.getSequencerStatus(sequencer2);
        (, bool isPriority3, uint8 idx3,,,,) = harness.getSequencerStatus(sequencer3);

        assertTrue(isPriority1 && isPriority2 && isPriority3, "All should be priority");
        assertEq(idx1, 0);
        assertEq(idx2, 1);
        assertEq(idx3, 2);
        assertEq(harness.getFirstLookSequencersLength(), 3);
    }

    function test_RemoveFirstLookUpdatesIndices() public {
        // Setup three priority sequencers
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        vm.prank(sequencer2);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer2);

        vm.prank(sequencer3);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer3);

        // Remove first element - seq3 should swap into index 0
        harness.removeFirstLook(0);

        assertEq(harness.getFirstLookSequencersLength(), 2);
        assertEq(harness.getFirstLookSequencer(0), sequencer3);
        assertEq(harness.getFirstLookSequencer(1), sequencer2);

        (, bool isPriority1,,,,,) = harness.getSequencerStatus(sequencer1);
        (,, uint8 idx2,,,,) = harness.getSequencerStatus(sequencer2);
        (,, uint8 idx3,,,,) = harness.getSequencerStatus(sequencer3);

        assertFalse(isPriority1, "seq1 should not be priority");
        assertEq(idx3, 0, "seq3 should have index 0");
        assertEq(idx2, 1, "seq2 should still have index 1");

        // Remove middle element - seq3 (now last) should swap into index 1
        harness.removeFirstLook(1);

        assertEq(harness.getFirstLookSequencersLength(), 1);
        assertEq(harness.getFirstLookSequencer(0), sequencer3);
    }

    function test_AddFirstLookRequiresActiveAndOwner() public {
        // Not active
        vm.expectRevert();
        harness.addFirstLook(sequencer1);

        // Not owner
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        vm.prank(sequencer1);
        vm.expectRevert();
        harness.addFirstLook(sequencer1);
    }

    function test_RemoveFirstLookOnlyOwner() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        vm.prank(sequencer1);
        vm.expectRevert();
        harness.removeFirstLook(0);
    }

    // ==================== isAllowed TESTS ====================

    function test_IsAllowedEmptyPriorityList() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        // Empty priority list during closed period allows anyone
        assertTrue(harness.isAllowed(sequencer1));
        assertTrue(harness.isAllowed(address(0x9999)));
    }

    function test_IsAllowedOpenPeriod() public {
        vm.prank(sequencer2);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer2);

        // Move to open period
        vm.warp(block.timestamp + EPOCH_LENGTH / 2 + 1);

        // Active with sufficient stake - allowed
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        assertTrue(harness.isAllowed(sequencer1));

        // Active with insufficient stake - not allowed
        vm.prank(sequencer3);
        harness.fund{value: 1 ether}();
        assertFalse(harness.isAllowed(sequencer3));

        // Not active - not allowed
        assertFalse(harness.isAllowed(address(0x9999)));
    }

    function test_IsAllowedClosedPeriod() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        vm.prank(sequencer2);
        harness.fund{value: 20 ether}();

        // In closed period, only designated priority sequencer allowed
        assertTrue(harness.isAllowed(sequencer1));
        assertFalse(harness.isAllowed(sequencer2));
    }

    function test_PriorityRotation() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        vm.prank(sequencer2);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer2);

        vm.prank(sequencer3);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer3);

        // Epoch 0: seq1
        assertTrue(harness.isAllowed(sequencer1));

        // Epoch 1: seq2
        vm.warp(block.timestamp + EPOCH_LENGTH);
        assertTrue(harness.isAllowed(sequencer2));

        // Epoch 2: seq3
        vm.warp(block.timestamp + EPOCH_LENGTH);
        assertTrue(harness.isAllowed(sequencer3));

        // Epoch 3: wraps to seq1
        vm.warp(block.timestamp + EPOCH_LENGTH);
        assertTrue(harness.isAllowed(sequencer1));
    }

    // ==================== SLASH TESTS ====================

    function test_SlashBasic() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        vm.prank(challenger);
        harness.slashSequencer(sequencer1, 5);

        (bool isActive,,, uint64 blockNum, uint64 timestamp,, address payable setChal) =
            harness.getSequencerStatus(sequencer1);

        assertFalse(isActive);
        assertEq(setChal, challenger);
        assertEq(blockNum, 5);
        assertEq(timestamp, block.timestamp);
    }

    function test_SlashChallengerPriority() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        address challenger2 = address(0x3001);
        address challenger3 = address(0x3002);

        // First slash at block 10
        vm.prank(challenger);
        harness.slashSequencer(sequencer1, 10);

        // Slash at block 5 (earlier) - should update
        vm.prank(challenger2);
        harness.slashSequencer(sequencer1, 5);

        (,,, uint64 blockNum,,, address payable setChal) = harness.getSequencerStatus(sequencer1);
        assertEq(setChal, challenger2, "Earlier challenger should take over");
        assertEq(blockNum, 5);

        // Slash at block 7 (later than 5) - should NOT update
        vm.prank(challenger3);
        harness.slashSequencer(sequencer1, 7);

        (,,, blockNum,,, setChal) = harness.getSequencerStatus(sequencer1);
        assertEq(setChal, challenger2, "Earlier challenger should remain");
        assertEq(blockNum, 5);

        // Slash at block 5 (equal) - should NOT update
        vm.prank(challenger3);
        harness.slashSequencer(sequencer1, 5);

        (,,,,,, setChal) = harness.getSequencerStatus(sequencer1);
        assertEq(setChal, challenger2, "Original challenger should remain");
    }

    function test_SlashRemovesPriority() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        assertEq(harness.getFirstLookSequencersLength(), 1);

        vm.prank(challenger);
        harness.slashSequencer(sequencer1, 0);

        (, bool isPriority,,,,,) = harness.getSequencerStatus(sequencer1);
        assertFalse(isPriority);
        assertEq(harness.getFirstLookSequencersLength(), 0);
    }

    // ==================== CLAIM CHALLENGE REWARD TESTS ====================

    function test_ClaimChallengeReward() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        uint256 balanceBefore = challenger.balance;

        vm.prank(challenger);
        harness.slashSequencer(sequencer1, 0);

        // Before window - should fail
        vm.expectRevert("Not ready");
        harness.claimChallengeReward(sequencer1);

        // After window - should succeed
        vm.warp(block.timestamp + CHALLENGE_WINDOW + 1);
        harness.claimChallengeReward(sequencer1);

        assertEq(challenger.balance, balanceBefore + 10 ether, "Should receive half stake");

        // Sequencer should be deleted
        (bool isActive,,,,, uint64 stakeAmount, address payable setChal) = harness.getSequencerStatus(sequencer1);
        assertFalse(isActive);
        assertEq(stakeAmount, 0);
        assertEq(setChal, address(0));
    }

    function test_ClaimChallengeRewardPayoutFails() public {
        RejectingContract rejecter = new RejectingContract();

        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        vm.prank(address(rejecter));
        harness.slashSequencer(sequencer1, 0);

        vm.warp(block.timestamp + CHALLENGE_WINDOW + 1);

        vm.expectRevert("Payout failed");
        harness.claimChallengeReward(sequencer1);
    }

    // ==================== EXIT TESTS ====================

    function test_RegisterExit() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();
        harness.addFirstLook(sequencer1);

        vm.prank(sequencer1);
        harness.registerExit();

        (bool isActive, bool isPriority,,,,,) = harness.getSequencerStatus(sequencer1);
        assertFalse(isActive);
        assertFalse(isPriority);
        assertEq(harness.exits(sequencer1), block.timestamp);
    }

    function test_Exit() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        uint256 balanceBefore = sequencer1.balance;

        vm.prank(sequencer1);
        harness.registerExit();

        // Before window - should fail
        vm.expectRevert("Exit pending");
        harness.exit(sequencer1);

        // After window - should succeed
        vm.warp(block.timestamp + CHALLENGE_WINDOW + 1);
        harness.exit(sequencer1);

        assertEq(sequencer1.balance, balanceBefore + 20 ether);
    }

    function test_ExitFailsIfChallenged() public {
        vm.prank(sequencer1);
        harness.fund{value: 20 ether}();

        vm.prank(sequencer1);
        harness.registerExit();

        vm.prank(challenger);
        harness.slashSequencer(sequencer1, 0);

        vm.warp(block.timestamp + CHALLENGE_WINDOW + 1);

        vm.expectRevert();
        harness.exit(sequencer1);
    }

    // ==================== OWNER FUNCTIONS TESTS ====================

    function test_UpdateStakeRequirement() public {
        harness.updateStakeRequirement(100000);
        assertEq(harness.requiredStake(), 100000);

        // At or above MAX_STAKE should fail
        vm.expectRevert();
        harness.updateStakeRequirement(2000000); // MAX_STAKE

        // Only owner
        vm.prank(sequencer1);
        vm.expectRevert();
        harness.updateStakeRequirement(100000);
    }
}
