// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Test} from "forge-std/Test.sol";
import {TransactionRegistry} from "../src/TransactionRegistry.sol";

// Note- Parts of the test code in this file was generated by claude code then human reviewed and edited

/// @notice Harness to expose internal hash computations for debugging
contract TransactionRegistryHarness is TransactionRegistry {
    function exposed_TYPE_HASH() external pure returns (bytes32) {
        return TYPE_HASH;
    }

    function exposed_customHash(bytes32[5] memory fields, address who) external pure returns (bytes32) {
        return customHash(fields, who);
    }
}

contract TransactionRegistryTests is Test {
    TransactionRegistry public registry;
    TransactionRegistryHarness public harness;

    // Test private key for signature tests
    uint256 constant SIGNER_PRIVATE_KEY = 0x1234567890abcdef1234567890abcdef1234567890abcdef1234567890abcdef;
    address signerAddress;

    function setUp() public {
        registry = new TransactionRegistry();
        harness = new TransactionRegistryHarness();
        signerAddress = vm.addr(SIGNER_PRIVATE_KEY);
    }

    // ========== Basic allow() and query() Tests ==========

    function test_allow_setsAllowedMapping() public {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        registry.allow(fields);

        // Should be queryable by the same sender
        bool isAllowed = registry.query(address(this), fields);
        assertTrue(isAllowed, "Should be allowed after allow() call");
    }

    function test_allow_emitsEvent() public {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        vm.expectEmit(true, false, false, true);
        emit TransactionRegistry.Allowed(address(this), fields);

        registry.allow(fields);
    }

    function test_query_returnsFalse_whenNotAllowed() public view {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        bool isAllowed = registry.query(address(this), fields);
        assertFalse(isAllowed, "Should not be allowed before allow() call");
    }

    function test_query_returnsFalse_withDifferentSender() public {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        registry.allow(fields);

        // Query with different sender should return false
        bool isAllowed = registry.query(address(0x1234), fields);
        assertFalse(isAllowed, "Should not be allowed with different sender");
    }

    function test_query_returnsFalse_withDifferentFields() public {
        bytes32[5] memory fields1 =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];
        bytes32[5] memory fields2 = [
            bytes32(uint256(1)),
            bytes32(uint256(2)),
            bytes32(uint256(3)),
            bytes32(uint256(4)),
            bytes32(uint256(6)) // Different last field
        ];

        registry.allow(fields1);

        bool isAllowed = registry.query(address(this), fields2);
        assertFalse(isAllowed, "Should not be allowed with different fields");
    }

    function testFuzz_allow_and_query(bytes32[5] memory fields) public {
        registry.allow(fields);
        assertTrue(registry.query(address(this), fields), "Fuzz: should be allowed after allow()");
    }

    // ========== approveByQuery() Tests ==========

    /// @notice Tests that approveByQuery works with a valid signature
    function test_approveByQuery_validSignature() public {
        TransactionRegistry.NullifiersAndNotes memory fields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [bytes32(uint256(1)), bytes32(uint256(2))],
            notes: [bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))],
            signer: signerAddress
        });

        bytes32 digest = _computeDigest(fields);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PRIVATE_KEY, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        registry.approveByQuery(fields, signature);

        // Verify the approval is queryable
        bytes32[5] memory arrayFields =
            [fields.nullifiers[0], fields.nullifiers[1], fields.notes[0], fields.notes[1], fields.notes[2]];
        assertTrue(registry.query(signerAddress, arrayFields), "Should be queryable after approveByQuery");
    }

    function test_approveByQuery_rejectsWrongSigner() public {
        TransactionRegistry.NullifiersAndNotes memory fields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [bytes32(uint256(1)), bytes32(uint256(2))],
            notes: [bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))],
            signer: address(0x9999) // Wrong signer
        });

        bytes32 digest = _computeDigest(fields);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PRIVATE_KEY, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        vm.expectRevert("Not signed");
        registry.approveByQuery(fields, signature);
    }

    function test_approveByQuery_rejectsInvalidSignature() public {
        TransactionRegistry.NullifiersAndNotes memory fields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [bytes32(uint256(1)), bytes32(uint256(2))],
            notes: [bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))],
            signer: signerAddress
        });

        // Create an invalid signature
        bytes memory invalidSignature = abi.encodePacked(bytes32(0), bytes32(0), uint8(27));

        vm.expectRevert(); // Should revert - either "Not signed" or ECDSA error
        registry.approveByQuery(fields, invalidSignature);
    }

    function test_approveByQuery_emitsEvent() public {
        TransactionRegistry.NullifiersAndNotes memory fields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [bytes32(uint256(1)), bytes32(uint256(2))],
            notes: [bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))],
            signer: signerAddress
        });

        bytes32 digest = _computeDigest(fields);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PRIVATE_KEY, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        bytes32[5] memory expectedFields =
            [fields.nullifiers[0], fields.nullifiers[1], fields.notes[0], fields.notes[1], fields.notes[2]];

        vm.expectEmit(true, false, false, true);
        emit TransactionRegistry.Allowed(signerAddress, expectedFields);

        registry.approveByQuery(fields, signature);
    }

    // ========== Hash Consistency Tests ==========

    /// @notice Verifies that approvals via approveByQuery can be queried via query()
    function test_hashConsistency_approveByQueryCanBeQueried() public {
        TransactionRegistry.NullifiersAndNotes memory structFields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [bytes32(uint256(1)), bytes32(uint256(2))],
            notes: [bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))],
            signer: signerAddress
        });

        bytes32 digest = _computeDigest(structFields);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PRIVATE_KEY, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        registry.approveByQuery(structFields, signature);

        // Now try to query with the equivalent bytes32[5] array
        bytes32[5] memory arrayFields = [
            structFields.nullifiers[0],
            structFields.nullifiers[1],
            structFields.notes[0],
            structFields.notes[1],
            structFields.notes[2]
        ];

        // This should return true - the hashes should be consistent
        bool isAllowed = registry.query(signerAddress, arrayFields);
        assertTrue(isAllowed, "approveByQuery approval should be queryable via query()");
    }

    /// @notice Tests that allow() and approveByQuery() produce consistent hashes
    function test_hashConsistency_allowAndApproveByQuerySameHash() public {
        // First, use allow() from signerAddress
        bytes32[5] memory arrayFields = [
            bytes32(uint256(100)),
            bytes32(uint256(200)),
            bytes32(uint256(300)),
            bytes32(uint256(400)),
            bytes32(uint256(500))
        ];

        vm.prank(signerAddress);
        registry.allow(arrayFields);

        // Verify it's queryable
        assertTrue(registry.query(signerAddress, arrayFields), "allow() should be queryable");

        // Now create equivalent struct for approveByQuery
        TransactionRegistry.NullifiersAndNotes memory structFields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [bytes32(uint256(100)), bytes32(uint256(200))],
            notes: [bytes32(uint256(300)), bytes32(uint256(400)), bytes32(uint256(500))],
            signer: signerAddress
        });

        bytes32 digest = _computeDigest(structFields);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PRIVATE_KEY, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        // This should succeed - it just sets allowed[hash] = true again
        registry.approveByQuery(structFields, signature);

        // Both should still be queryable
        assertTrue(registry.query(signerAddress, arrayFields), "Should remain queryable after double approval");
    }

    // ========== EIP-712 Tests ==========

    /// @notice Verifies the TYPE_HASH matches expected value
    function test_eip712_typeHash() public view {
        bytes32 expectedTypeHash =
            keccak256("NullifiersAndNotes(bytes32[2] nullifiers,bytes32[3] notes,address signer)");
        bytes32 actualTypeHash = harness.exposed_TYPE_HASH();
        assertEq(actualTypeHash, expectedTypeHash, "TYPE_HASH should match expected value");
    }

    // ========== Edge Cases ==========

    function test_allow_zeroFields() public {
        bytes32[5] memory fields = [bytes32(0), bytes32(0), bytes32(0), bytes32(0), bytes32(0)];

        registry.allow(fields);
        assertTrue(registry.query(address(this), fields), "Should allow zero fields");
    }

    function test_allow_maxFields() public {
        bytes32[5] memory fields = [
            bytes32(type(uint256).max),
            bytes32(type(uint256).max),
            bytes32(type(uint256).max),
            bytes32(type(uint256).max),
            bytes32(type(uint256).max)
        ];

        registry.allow(fields);
        assertTrue(registry.query(address(this), fields), "Should allow max fields");
    }

    function test_allow_multipleTimes_sameSender() public {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        registry.allow(fields);
        registry.allow(fields); // Allow again

        assertTrue(registry.query(address(this), fields), "Should still be allowed after double allow");
    }

    function test_allow_differentSenders_sameFields() public {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        address sender1 = address(0x1111);
        address sender2 = address(0x2222);

        vm.prank(sender1);
        registry.allow(fields);

        vm.prank(sender2);
        registry.allow(fields);

        // Both should be independently allowed
        assertTrue(registry.query(sender1, fields), "Sender1 should be allowed");
        assertTrue(registry.query(sender2, fields), "Sender2 should be allowed");
    }

    /// @notice Tests the direct hash stored in the allowed mapping
    function test_allowedMapping_directAccess() public {
        bytes32[5] memory fields =
            [bytes32(uint256(1)), bytes32(uint256(2)), bytes32(uint256(3)), bytes32(uint256(4)), bytes32(uint256(5))];

        // Compute what we think the hash should be using the harness
        bytes32 expectedHash = harness.exposed_customHash(fields, address(this));

        registry.allow(fields);

        // Check if the hash in the mapping matches our expectation
        assertTrue(registry.allowed(expectedHash), "Hash computation should match our expectation");
    }

    // ========== Fuzz Tests ==========

    function testFuzz_NoNonApproval(
        bytes32[5] memory real,
        address realSender,
        bytes32[5] memory fake,
        address fakeSender
    ) public {
        vm.prank(realSender);
        registry.allow(real);
        assertFalse(registry.query(fakeSender, fake));
    }

    function testFuzz_approveByQuery(
        bytes32 nullifier0,
        bytes32 nullifier1,
        bytes32 note0,
        bytes32 note1,
        bytes32 note2
    ) public {
        TransactionRegistry.NullifiersAndNotes memory fields = TransactionRegistry.NullifiersAndNotes({
            nullifiers: [nullifier0, nullifier1], notes: [note0, note1, note2], signer: signerAddress
        });

        bytes32 digest = _computeDigest(fields);
        (uint8 v, bytes32 r, bytes32 s) = vm.sign(SIGNER_PRIVATE_KEY, digest);
        bytes memory signature = abi.encodePacked(r, s, v);

        registry.approveByQuery(fields, signature);

        bytes32[5] memory arrayFields = [nullifier0, nullifier1, note0, note1, note2];
        assertTrue(registry.query(signerAddress, arrayFields), "Fuzz: should be queryable after approveByQuery");
    }

    // ========== Helper Functions ==========

    function _computeDigest(TransactionRegistry.NullifiersAndNotes memory fields) internal view returns (bytes32) {
        // Compute the struct hash the same way as the contract
        // Order matches TYPE_HASH: nullifiers, notes, signer
        bytes32 typeHash = keccak256("NullifiersAndNotes(bytes32[2] nullifiers,bytes32[3] notes,address signer)");
        bytes32 structHash = keccak256(
            abi.encodePacked(
                typeHash,
                keccak256(abi.encodePacked(fields.nullifiers)),
                keccak256(abi.encodePacked(fields.notes)),
                fields.signer
            )
        );

        // Use EIP-712 typed data hash
        // Domain separator components from contract constructor: ("PaymentApproval", "1")
        bytes32 domainSeparator = keccak256(
            abi.encode(
                keccak256("EIP712Domain(string name,string version,uint256 chainId,address verifyingContract)"),
                keccak256(bytes("PaymentApproval")),
                keccak256(bytes("1")),
                block.chainid,
                address(registry)
            )
        );

        return keccak256(abi.encodePacked("\x19\x01", domainSeparator, structHash));
    }
}
