// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.28;

// Note- Parts of the test code in this file was generated by ai then human reviewed

import {Test} from "forge-std/Test.sol";
import {Withdraw} from "../src/Withdraw.sol";
import {Spine} from "../src/Spine.sol";
import {PredictableMerkleLib, Leaf} from "../src/library/PredictableMerkleLib.sol";
import {IYieldRouter} from "../src/interfaces/IYieldRouter.sol";
import {IUpdateVerifier} from "../src/interfaces/IUpdateVerifier.sol";
import {ITransferVerifier} from "../src/interfaces/ITransferVerifier.sol";
import {ITransactionRegistry} from "../src/TransactionRegistry.sol";
import {FakeBlobs} from "./mocks/FakeBlobs.sol";
import {MockYieldRouter} from "./mocks/MockYieldRouter.sol";
import {MockTransactionRegistry} from "./mocks/MockTransactionRegistry.sol";
import {FakeZK} from "./mocks/FakeZk.sol";
import {FakeERC20} from "./mocks/FakeErc20.sol";
import {
    BlockNotConfirmed,
    PublicKeyNotZero,
    AlreadyWithdrawn,
    InvalidLeafWhich,
    TxIndexOutOfBounds
} from "../src/library/Errors.sol";

contract WithdrawHarness is Withdraw, FakeBlobs {
    constructor(
        bytes32 genesis,
        IYieldRouter _yieldRouter,
        IUpdateVerifier _updateVerifier,
        ITransferVerifier _transferVerifier,
        ITransactionRegistry _txRegistry
    ) {
        GENESIS_ANCHOR = genesis;
        yieldRouter = _yieldRouter;
        predictableUpdateVerifier = _updateVerifier;
        transactionZkVerifier = _transferVerifier;
        transferRegistry = _txRegistry;
    }

    // Override validateSingle to use FakeBlobs storage instead of KZG proofs
    function validateSingle(bytes32 rootHash, bytes calldata, uint256 index, bytes32 data, bytes calldata)
        internal
        view
        override
    {
        require(access(rootHash, index) == data, "Blob data mismatch");
    }

    // Setup block data with random blob content
    function setupBlocks(BlockData memory data, uint256 seed) public returns (BlockData memory, bytes32[] memory ret) {
        uint256 depositSize = data.numDeposits % 3 == 0 ? (data.numDeposits / 3) * 4 : (data.numDeposits / 3 + 1) * 4;
        uint256 dataNeeded = depositSize + data.numTransactions * 15;
        bytes32[] memory randomData = new bytes32[](dataNeeded);
        for (uint256 i = 0; i < dataNeeded; i++) {
            randomData[i] = keccak256(abi.encodePacked(i, seed));
        }
        ret = store(randomData);
        data.blobhashes = ret;
        return (data, ret);
    }

    // Add block to the chain
    function addBlockTest(BlockData memory data, uint256[] memory indices) public returns (BlockData memory) {
        addBlock(data, indices);
        return data;
    }

    // Helper to set a value at a logical index in blob storage
    function setValueAt(bytes32 blobHash, uint256 logicalIndex, bytes32 value) public {
        uint256 storageIndex = bitReverse(logicalIndex);
        storeAt(blobHash, storageIndex, value);
    }

    // Expose leafMemoryAddress for testing
    function getLeafMemoryAddress(uint256 number, uint256 numDeposits, bool isDeposit, uint256 which)
        public
        pure
        returns (uint256)
    {
        return leafMemoryAddress(number, numDeposits, isDeposit, which);
    }

    // Expose withdrawn mapping - key formula: (txNr << 2) + which
    function isWithdrawn(uint256 blockNr, uint256 txNr, uint256 which) public view returns (bool) {
        return withdrawn[blockNr][(txNr << 2) + which];
    }

    // Expose CHALLENGE_PERIOD constant
    function getChallengePeriod() public pure returns (uint256) {
        return CHALLENGE_PERIOD;
    }

    // Expose getCurrentBlocknumber
    function getBlockCount() public view returns (uint256) {
        return getCurrentBlocknumber();
    }

    receive() external payable {}
}

contract WithdrawTest is Test {
    using PredictableMerkleLib for Leaf;

    WithdrawHarness harness;
    MockYieldRouter yieldRouter;
    FakeZK fakeZk;
    MockTransactionRegistry txRegistry;
    FakeERC20 token;

    uint256 constant YIELD_ROUTER_BALANCE = 1_000_000 ether;

    function setUp() public {
        yieldRouter = new MockYieldRouter();
        fakeZk = new FakeZK();
        txRegistry = new MockTransactionRegistry();
        token = new FakeERC20();

        // Mint tokens to yield router so it can pay out withdrawals
        token.mint(address(yieldRouter), YIELD_ROUTER_BALANCE);

        harness = new WithdrawHarness(keccak256("genesis"), yieldRouter, fakeZk, fakeZk, txRegistry);
    }

    // Helper to create a confirmed block with a valid leaf at a specific position
    function _createConfirmedBlockWithLeaf(
        Leaf memory leaf,
        uint256 txNr,
        uint256 which,
        uint256 numTransactions,
        uint256 numDeposits,
        uint256 seed
    ) internal returns (Spine.BlockData memory, bytes32[] memory) {
        bytes32 anchor = keccak256(abi.encodePacked("anchor", seed));

        Spine.BlockData memory blockData = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: numTransactions,
            numDeposits: numDeposits,
            blockNr: harness.getBlockCount(),
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](1)
        });

        (blockData,) = harness.setupBlocks(blockData, seed);
        bytes32[] memory blobhashes = blockData.blobhashes;

        // Set the leaf hash at the correct position
        bytes32 leafHash = leaf.hash();
        uint256 memAddress = harness.getLeafMemoryAddress(txNr, numDeposits, false, which);
        uint256 blobIndex = memAddress / 4096;
        uint256 posInBlob = memAddress % 4096;

        harness.setValueAt(blobhashes[blobIndex], posInBlob, leafHash);

        // Setup vm.blobhashes and add block
        vm.blobhashes(blobhashes);
        uint256[] memory indices = new uint256[](blobhashes.length);
        for (uint256 i = 0; i < blobhashes.length; i++) {
            indices[i] = i;
        }
        blockData = harness.addBlockTest(blockData, indices);

        // Warp past challenge period to confirm the block
        // Use blockData.timestamp (captured at function start) to avoid via_ir optimizer issues
        uint256 challengePeriod = harness.getChallengePeriod();
        vm.warp(blockData.timestamp + challengePeriod + 1);

        return (blockData, blobhashes);
    }

    // ==================== BASIC WITHDRAW TESTS ====================

    function test_BasicWithdraw() public {
        address recipient = address(0xBEEF);
        uint256 amount = 100 ether;
        Leaf memory leaf = Leaf({
            asset: address(token), amount: amount, blinding: bytes32(uint256(uint160(recipient))), publicKey: bytes32(0)
        });

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, 0, 0, 1, 0, 12345);

        uint256 recipientBalanceBefore = token.balanceOf(recipient);
        uint256 yieldRouterBalanceBefore = token.balanceOf(address(yieldRouter));

        harness.withdraw(leaf, blockData, 0, 0, "", "");

        assertTrue(harness.isWithdrawn(blockData.blockNr, 0, 0), "Correct key should be marked");
        assertEq(token.balanceOf(recipient), recipientBalanceBefore + amount, "Recipient should receive tokens");
        assertEq(
            token.balanceOf(address(yieldRouter)), yieldRouterBalanceBefore - amount, "YieldRouter should send tokens"
        );
    }

    function test_WithdrawRevertsIfNotConfirmed() public {
        address recipient = address(0xBEEF);
        Leaf memory leaf = Leaf({
            asset: address(token),
            amount: 100 ether,
            blinding: bytes32(uint256(uint160(recipient))),
            publicKey: bytes32(0)
        });

        bytes32 anchor = keccak256("anchor");
        Spine.BlockData memory blockData = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: 1,
            numDeposits: 0,
            blockNr: harness.getBlockCount(),
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](1)
        });

        (blockData,) = harness.setupBlocks(blockData, 111);
        vm.blobhashes(blockData.blobhashes);

        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        blockData = harness.addBlockTest(blockData, indices);

        // Don't warp - block is not confirmed yet
        vm.expectRevert(BlockNotConfirmed.selector);
        harness.withdraw(leaf, blockData, 0, 0, "", "");
    }

    function test_WithdrawRevertsIfPublicKeyNotZero() public {
        address recipient = address(0xBEEF);
        Leaf memory leaf = Leaf({
            asset: address(token),
            amount: 100 ether,
            blinding: bytes32(uint256(uint160(recipient))),
            publicKey: bytes32(uint256(1)) // Non-zero - should fail
        });

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, 0, 0, 1, 0, 222);

        vm.expectRevert(PublicKeyNotZero.selector);
        harness.withdraw(leaf, blockData, 0, 0, "", "");
    }

    // ==================== KEY CALCULATION TESTS ====================
    // Verify that the key calculation (txNr << 2) + which is consistent
    // and properly prevents double withdrawals for all which values

    function test_DoubleWithdrawPrevented_AllWhichValues() public {
        // Test that double withdrawal is correctly prevented for all which values (0, 1, 2)
        address recipient = address(0xBEEF);
        uint256 amount = 100 ether;

        for (uint256 which = 0; which < 3; which++) {
            Leaf memory leaf = Leaf({
                asset: address(token),
                amount: amount,
                blinding: bytes32(uint256(uint160(recipient))),
                publicKey: bytes32(0)
            });

            (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, 1, which, 2, 0, 999 + which);

            uint256 recipientBalanceBefore = token.balanceOf(recipient);

            // First withdrawal should succeed
            harness.withdraw(leaf, blockData, 1, which, "", "");

            // Verify the correct key is marked and tokens transferred
            assertTrue(harness.isWithdrawn(blockData.blockNr, 1, which), "Withdrawal should be marked");
            assertEq(token.balanceOf(recipient), recipientBalanceBefore + amount, "Recipient should receive tokens");

            // Second withdrawal should fail
            vm.expectRevert(AlreadyWithdrawn.selector);
            harness.withdraw(leaf, blockData, 1, which, "", "");
        }
    }

    // ==================== BOUNDARY TESTS ====================

    function test_WithdrawWhichBoundary() public {
        address recipient = address(0xBEEF);
        Leaf memory leaf = Leaf({
            asset: address(token),
            amount: 100 ether,
            blinding: bytes32(uint256(uint160(recipient))),
            publicKey: bytes32(0)
        });

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, 0, 0, 1, 0, 666);

        // which = 3 should fail (require which < 3)
        vm.expectRevert(InvalidLeafWhich.selector);
        harness.withdraw(leaf, blockData, 0, 3, "", "");
    }

    function test_WithdrawTxNrBoundary() public {
        address recipient = address(0xBEEF);
        Leaf memory leaf = Leaf({
            asset: address(token),
            amount: 100 ether,
            blinding: bytes32(uint256(uint160(recipient))),
            publicKey: bytes32(0)
        });

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, 0, 0, 1, 0, 777);

        // txNr >= numTransactions should fail
        vm.expectRevert(TxIndexOutOfBounds.selector);
        harness.withdraw(leaf, blockData, 1, 0, "", "");
    }

    // ==================== DEPOSIT OFFSET TESTS ====================

    function test_WithdrawWithDeposits() public {
        // Test withdrawal when there are deposits in the block
        address recipient = address(0xBEEF);
        uint256 amount = 100 ether;
        Leaf memory leaf = Leaf({
            asset: address(token), amount: amount, blinding: bytes32(uint256(uint160(recipient))), publicKey: bytes32(0)
        });

        (Spine.BlockData memory blockData,) =
            _createConfirmedBlockWithLeaf(
                leaf,
                0,
                0,
                1,
                5,
                1111 // 5 deposits affects memory layout
            );

        uint256 recipientBalanceBefore = token.balanceOf(recipient);
        harness.withdraw(leaf, blockData, 0, 0, "", "");
        assertEq(token.balanceOf(recipient), recipientBalanceBefore + amount, "Recipient should receive tokens");
    }

    // ==================== MULTI-BLOB TESTS ====================

    function test_WithdrawFromSecondBlob() public {
        address recipient = address(0xBEEF);
        uint256 amount = 100 ether;
        Leaf memory leaf = Leaf({
            asset: address(token), amount: amount, blinding: bytes32(uint256(uint160(recipient))), publicKey: bytes32(0)
        });

        uint256 numTx = 300; // This will span into second blob
        uint256 txNr = 280; // This tx should be in second blob

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, txNr, 0, numTx, 0, 3000);

        uint256 memAddress = harness.getLeafMemoryAddress(txNr, 0, false, 0);
        uint256 blobIndex = memAddress / 4096;

        assertTrue(blobIndex > 0, "Transaction should be in second blob");

        uint256 recipientBalanceBefore = token.balanceOf(recipient);
        // blobIndex is now derived internally from txNr
        harness.withdraw(leaf, blockData, txNr, 0, "", "");
        assertEq(token.balanceOf(recipient), recipientBalanceBefore + amount, "Recipient should receive tokens");
    }

    // ==================== FUZZ TESTS ====================

    function testFuzz_WithdrawAllWhichValues(uint256 seed, uint8 numTx, uint8 whichVal) public {
        // Test withdrawals for all valid which values (0, 1, 2)
        numTx = uint8(bound(numTx, 1, 50));
        whichVal = uint8(bound(whichVal, 0, 2));

        address recipient = address(uint160(seed % type(uint160).max));
        if (recipient == address(0)) recipient = address(1);

        uint256 amount = bound(seed, 1, 1000 ether);
        Leaf memory leaf = Leaf({
            asset: address(token), amount: amount, blinding: bytes32(uint256(uint160(recipient))), publicKey: bytes32(0)
        });

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, 0, whichVal, numTx, 0, seed);

        uint256 recipientBalanceBefore = token.balanceOf(recipient);
        harness.withdraw(leaf, blockData, 0, whichVal, "", "");
        assertTrue(harness.isWithdrawn(blockData.blockNr, 0, whichVal), "Should be marked withdrawn");
        assertEq(token.balanceOf(recipient), recipientBalanceBefore + amount, "Recipient should receive tokens");
    }

    function testFuzz_DoubleWithdrawPrevention(uint256 seed, uint8 txNr, uint8 whichVal) public {
        // Verify double withdrawal is always prevented
        txNr = uint8(bound(txNr, 0, 10));
        whichVal = uint8(bound(whichVal, 0, 2));
        uint8 numTx = txNr + 1;

        address recipient = address(uint160(seed % type(uint160).max));
        if (recipient == address(0)) recipient = address(1);

        uint256 amount = bound(seed, 1, 1000 ether);
        Leaf memory leaf = Leaf({
            asset: address(token), amount: amount, blinding: bytes32(uint256(uint160(recipient))), publicKey: bytes32(0)
        });

        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(leaf, txNr, whichVal, numTx, 0, seed);

        uint256 recipientBalanceBefore = token.balanceOf(recipient);

        // First withdrawal succeeds
        harness.withdraw(leaf, blockData, txNr, whichVal, "", "");
        assertEq(token.balanceOf(recipient), recipientBalanceBefore + amount, "Recipient should receive tokens");

        // Second withdrawal should always fail (no additional tokens transferred)
        vm.expectRevert(AlreadyWithdrawn.selector);
        harness.withdraw(leaf, blockData, txNr, whichVal, "", "");
        assertEq(
            token.balanceOf(recipient),
            recipientBalanceBefore + amount,
            "Balance should not change after failed withdrawal"
        );
    }

    // ==================== ADDITIONAL COVERAGE TESTS ====================

    function test_MultipleWithdrawalsFromSameBlock() public {
        // Test withdrawing multiple different outputs from the same block
        address recipient1 = address(0xBEEF);
        address recipient2 = address(0xCAFE);
        address recipient3 = address(0xDEAD);
        uint256 amount1 = 100 ether;
        uint256 amount2 = 200 ether;
        uint256 amount3 = 300 ether;

        // Create leaves for different txNr/which combinations
        Leaf memory leaf1 = Leaf({
            asset: address(token),
            amount: amount1,
            blinding: bytes32(uint256(uint160(recipient1))),
            publicKey: bytes32(0)
        });

        Leaf memory leaf2 = Leaf({
            asset: address(token),
            amount: amount2,
            blinding: bytes32(uint256(uint160(recipient2))),
            publicKey: bytes32(0)
        });

        Leaf memory leaf3 = Leaf({
            asset: address(token),
            amount: amount3,
            blinding: bytes32(uint256(uint160(recipient3))),
            publicKey: bytes32(0)
        });

        // Create a block with multiple transactions
        bytes32 anchor = keccak256("multi-withdraw-anchor");
        uint256 numTx = 2;
        uint256 numDeposits = 0;

        Spine.BlockData memory blockData = Spine.BlockData({
            anchor: anchor,
            timestamp: block.timestamp,
            numTransactions: numTx,
            numDeposits: numDeposits,
            blockNr: harness.getBlockCount(),
            blockIndex: Spine.TimestampAndIndex(0, 0),
            sequencer: address(this),
            blobhashes: new bytes32[](1)
        });

        (blockData,) = harness.setupBlocks(blockData, 5555);
        bytes32[] memory blobhashes = blockData.blobhashes;

        // Set leaves at different positions
        // tx0, which=0
        harness.setValueAt(blobhashes[0], harness.getLeafMemoryAddress(0, numDeposits, false, 0) % 4096, leaf1.hash());
        // tx0, which=1
        harness.setValueAt(blobhashes[0], harness.getLeafMemoryAddress(0, numDeposits, false, 1) % 4096, leaf2.hash());
        // tx1, which=0
        harness.setValueAt(blobhashes[0], harness.getLeafMemoryAddress(1, numDeposits, false, 0) % 4096, leaf3.hash());

        vm.blobhashes(blobhashes);
        uint256[] memory indices = new uint256[](1);
        indices[0] = 0;
        blockData = harness.addBlockTest(blockData, indices);
        uint256 challengePeriod = harness.getChallengePeriod();
        vm.warp(block.timestamp + challengePeriod + 1);

        uint256 yieldRouterBalanceBefore = token.balanceOf(address(yieldRouter));

        // Withdraw all three - should all succeed since they use different keys
        harness.withdraw(leaf1, blockData, 0, 0, "", "");
        harness.withdraw(leaf2, blockData, 0, 1, "", "");
        harness.withdraw(leaf3, blockData, 1, 0, "", "");

        // Verify all are marked as withdrawn
        assertTrue(harness.isWithdrawn(blockData.blockNr, 0, 0), "leaf1 should be withdrawn");
        assertTrue(harness.isWithdrawn(blockData.blockNr, 0, 1), "leaf2 should be withdrawn");
        assertTrue(harness.isWithdrawn(blockData.blockNr, 1, 0), "leaf3 should be withdrawn");

        // Verify each recipient received their tokens
        assertEq(token.balanceOf(recipient1), amount1, "Recipient1 should receive tokens");
        assertEq(token.balanceOf(recipient2), amount2, "Recipient2 should receive tokens");
        assertEq(token.balanceOf(recipient3), amount3, "Recipient3 should receive tokens");

        // Verify yield router balance decreased correctly
        assertEq(
            token.balanceOf(address(yieldRouter)),
            yieldRouterBalanceBefore - amount1 - amount2 - amount3,
            "YieldRouter should have sent total tokens"
        );
    }

    function test_WithdrawWrongLeafDataFails() public {
        // Test that providing wrong leaf data fails validation
        address recipient = address(0xBEEF);
        Leaf memory correctLeaf = Leaf({
            asset: address(token),
            amount: 100 ether,
            blinding: bytes32(uint256(uint160(recipient))),
            publicKey: bytes32(0)
        });

        // Create a confirmed block with the correct leaf
        (Spine.BlockData memory blockData,) = _createConfirmedBlockWithLeaf(correctLeaf, 0, 0, 1, 0, 6666);

        // Try to withdraw with different leaf data
        Leaf memory wrongLeaf = Leaf({
            asset: address(token),
            amount: 999 ether, // Different amount
            blinding: bytes32(uint256(uint160(recipient))),
            publicKey: bytes32(0)
        });

        vm.expectRevert("Blob data mismatch");
        harness.withdraw(wrongLeaf, blockData, 0, 0, "", "");
    }
}
