// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

// Note- Parts of the test code in this file was generated by ai then human reviewed

import "forge-std/Test.sol";
import "../src/YieldRouter.sol";
import "./mocks/FakeErc20.sol";
import "./mocks/MockERC4626.sol";

// Harness to set state and call internal functions for testing
contract YieldRouterHarness is YieldRouter {
    constructor(uint256 periodLength, uint256 epochPerPeriod, address _bridge, address[] memory tracked)
        YieldRouter(periodLength, epochPerPeriod, _bridge, tracked)
    {
        _initializeOwner(msg.sender);
    }

    // Arrays don't expose .length via auto-generated getters
    function getTrackedYieldSourcesLength() external view returns (uint256) {
        return trackedYieldSources.length;
    }

    // Functions to set state for testing (bypassing restrictions)
    function setSource(address token, IERC4626 source) external {
        sources[token] = source;
    }

    function setPriorBalance(address token, uint256 balance) external {
        priorBalances[token] = balance;
    }

    function addTrackedYieldSource(address token) external {
        address[] memory newSources = new address[](trackedYieldSources.length + 1);
        for (uint256 i = 0; i < trackedYieldSources.length; i++) {
            newSources[i] = trackedYieldSources[i];
        }
        newSources[trackedYieldSources.length] = token;
        trackedYieldSources = newSources;
    }

    function setPeriodPayout(address token, uint256 period, uint256 amount) external {
        periodPayouts[token][period] = amount;
    }

    function setSequencerPercent(address sequencer, uint256 epoch, uint256 percent) external {
        sequencerPercents[sequencer][epoch] = percent;
    }

    // Direct call to internal _record for testing
    function recordYield(address token, uint256 period) external {
        _record(token, period);
    }

    // Bypass bridge restriction for testing deposit/withdraw
    function testTriggerDeposit(address asset, uint256 amount) external {
        require(IERC20(asset).balanceOf(address(this)) >= amount, "Not Transferred");
        require(address(sources[asset]) != address(0), "ERC20 not enabled");
        priorBalances[asset] += amount;
        sources[asset].deposit(amount, address(this));
    }

    function testTriggerWithdraw(address asset, uint256 amount, address destination) external {
        uint256 totalShares = sources[asset].balanceOf(address(this));
        uint256 currentGlobalValue = sources[asset].previewRedeem(totalShares);
        uint256 userAmount = amount;
        if (priorBalances[asset] > currentGlobalValue) {
            uint256 fixedPercent = (priorBalances[asset] * 1e18) / currentGlobalValue;
            userAmount = fixedPercent * amount / 1e18;
        }
        sources[asset].withdraw(userAmount, destination, address(this));
        priorBalances[asset] -= userAmount;
    }

    function testReportPayoutPercent(address sequencer, uint256 percent, uint256 epoch) external {
        poke();
        if (percent <= 1e18) {
            sequencerPercents[sequencer][epoch] = percent;
        }
    }
}

contract YieldRouterTest is Test {
    YieldRouterHarness router;
    FakeERC20 token;
    MockERC4626 vault;

    address user = address(0xBEEF);
    address sequencer1 = address(0x1001);
    address sequencer2 = address(0x1002);
    address bridge = address(0xBBBB);

    uint256 constant PERIOD_LENGTH = 1 days;
    uint256 constant EPOCHS_PER_PERIOD = 10;

    function setUp() public {
        token = new FakeERC20();
        vault = new MockERC4626(token);

        // Create router with empty tracked sources initially
        address[] memory emptyTracked = new address[](0);
        router = new YieldRouterHarness(PERIOD_LENGTH, EPOCHS_PER_PERIOD, bridge, emptyTracked);

        // Setup: configure vault as source
        router.setSource(address(token), vault);
        token.approve(address(vault), type(uint256).max);

        // Approve router to spend tokens
        vm.startPrank(address(router));
        token.approve(address(vault), type(uint256).max);
        vm.stopPrank();
    }

    // ==================== BRIDGE TESTS ====================

    function test_BridgeCorrectlyInitialized() public {
        // The bridge address is properly set in constructor
        // Verify bridge can call onlyBridge functions

        // Fund router with tokens
        token.mint(address(router), 100 ether);
        router.setSource(address(token), vault);

        // Call triggerDeposit as bridge - should succeed
        vm.prank(bridge);
        router.triggerDeposit(address(token), 100 ether);

        assertEq(router.priorBalances(address(token)), 100 ether, "Deposit should work via bridge");
    }

    function test_NonBridgeCannotCallOnlyBridge() public {
        token.mint(address(router), 100 ether);
        router.setSource(address(token), vault);

        // Non-bridge address should fail
        vm.prank(user);
        vm.expectRevert();
        router.triggerDeposit(address(token), 100 ether);
    }

    function test_TriggerWithdraw_ViaBridge() public {
        token.mint(address(router), 100 ether);

        vm.prank(bridge);
        router.triggerDeposit(address(token), 100 ether);

        vm.prank(bridge);
        router.triggerWithdraw(address(token), 50 ether, user);

        assertEq(token.balanceOf(user), 50 ether, "User receives withdrawal");
        assertEq(router.priorBalances(address(token)), 50 ether, "Prior balance updated");
    }

    function test_TriggerWithdraw_ViaBridge_WithLoss() public {
        token.mint(address(router), 100 ether);

        vm.prank(bridge);
        router.triggerDeposit(address(token), 100 ether);

        // Simulate loss
        vault.simulateLoss(20 ether);

        vm.prank(bridge);
        router.triggerWithdraw(address(token), 20 ether, user);

        // Loss triggers proportional adjustment
        uint256 received = token.balanceOf(user);
        assertTrue(received > 0, "User receives tokens");
        assertEq(router.priorBalances(address(token)), 100 ether - received, "Prior balance tracks withdrawal");
    }

    function test_ReportPayoutPercent_ViaBridge() public {
        vm.prank(bridge);
        router.reportPayoutPercent(sequencer1, 0.5e18, 0);

        assertEq(router.sequencerPercents(sequencer1, 0), 0.5e18, "Percent recorded via bridge");
    }

    // ==================== DEPOSIT TESTS ====================

    function test_TriggerDeposit_Basic() public {
        token.mint(address(router), 100 ether);

        router.testTriggerDeposit(address(token), 100 ether);

        assertEq(router.priorBalances(address(token)), 100 ether, "Prior balance should be set");
        assertEq(vault.balanceOf(address(router)), 100 ether, "Router should have vault shares");
    }

    function test_TriggerDeposit_RequiresTokensTransferred() public {
        // Don't transfer tokens first
        vm.expectRevert("Not Transferred");
        router.testTriggerDeposit(address(token), 100 ether);
    }

    function test_TriggerDeposit_RequiresSourceEnabled() public {
        FakeERC20 otherToken = new FakeERC20();
        otherToken.mint(address(router), 100 ether);

        // Source not set for otherToken
        vm.expectRevert("ERC20 not enabled");
        router.testTriggerDeposit(address(otherToken), 100 ether);
    }

    // ==================== WITHDRAW TESTS ====================

    function test_TriggerWithdraw_Basic() public {
        // Setup: deposit first
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Withdraw
        router.testTriggerWithdraw(address(token), 50 ether, user);

        assertEq(token.balanceOf(user), 50 ether, "User should receive tokens");
        assertEq(router.priorBalances(address(token)), 50 ether, "Prior balance should decrease");
    }

    function test_WithdrawWithLoss_ProportionalReduction() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Simulate 20% loss (vault now has 80 ether)
        vault.simulateLoss(20 ether);

        uint256 userBalanceBefore = token.balanceOf(user);
        router.testTriggerWithdraw(address(token), 50 ether, user);
        uint256 received = token.balanceOf(user) - userBalanceBefore;

        // Loss triggers proportional adjustment: fixedPercent = 100/80 = 1.25
        // userAmount = 1.25 * 50 = 62.5 ether
        assertTrue(received > 0, "User should receive tokens");
        assertEq(router.priorBalances(address(token)), 100 ether - received, "Prior balance tracks withdrawal");
    }

    function test_WithdrawWithLoss_SmallWithdrawal() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.simulateLoss(20 ether);

        uint256 userBalanceBefore = token.balanceOf(user);
        router.testTriggerWithdraw(address(token), 20 ether, user);
        uint256 received = token.balanceOf(user) - userBalanceBefore;

        // fixedPercent = 100/80 = 1.25, userAmount = 1.25 * 20 = 25 ether
        assertEq(received, 25 ether, "User receives calculated amount during loss");
        assertEq(router.priorBalances(address(token)), 75 ether, "Prior balance decreased by userAmount");
    }

    function test_WithdrawWithProfit_NoReduction() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(20 ether);

        uint256 userBalanceBefore = token.balanceOf(user);
        router.testTriggerWithdraw(address(token), 60 ether, user);
        uint256 received = token.balanceOf(user) - userBalanceBefore;

        // No reduction during profit - user gets full requested amount
        assertEq(received, 60 ether, "User receives full amount during profit");
        assertEq(router.priorBalances(address(token)), 40 ether, "Prior balance correctly decreased");
    }

    // ==================== CURRENT PERIOD TESTS ====================

    function test_CurrentPeriod_Basic() public {
        // currentPeriod() uses / to return the period NUMBER

        // At time 0, period should be 0
        assertEq(router.currentPeriod(), 0, "Period at start should be 0");

        // After exactly 1 period
        vm.warp(block.timestamp + PERIOD_LENGTH);
        assertEq(router.currentPeriod(), 1, "After 1 period should be period 1");

        // After 1.5 periods, should still be period 1
        vm.warp(block.timestamp + PERIOD_LENGTH / 2);
        assertEq(router.currentPeriod(), 1, "Halfway through period 2 should still be period 1");

        // After 2 full periods
        vm.warp(block.timestamp + PERIOD_LENGTH / 2);
        assertEq(router.currentPeriod(), 2, "After 2 periods should be period 2");
    }

    // ==================== SEQUENCER PAYOUT TESTS ====================

    function test_MultiTokenWithdrawals_SameEpoch() public {
        // Setup second token and vault
        FakeERC20 token2 = new FakeERC20();
        MockERC4626 vault2 = new MockERC4626(token2);
        router.setSource(address(token2), vault2);

        // Deposit both tokens
        token.mint(address(router), 100 ether);
        token2.mint(address(router), 100 ether);

        vm.startPrank(address(router));
        token2.approve(address(vault2), type(uint256).max);
        vm.stopPrank();

        router.testTriggerDeposit(address(token), 100 ether);

        // Setup token2 deposit manually since we need separate handling
        vm.startPrank(address(router));
        token2.approve(address(vault2), type(uint256).max);
        vault2.deposit(100 ether, address(router));
        vm.stopPrank();
        router.setPriorBalance(address(token2), 100 ether);

        // Add yield to both vaults
        vault.addYield(10 ether);
        vault2.addYield(10 ether);

        // Setup period payout and sequencer percent
        uint256 epoch = 0;
        uint256 period = epoch / EPOCHS_PER_PERIOD;
        router.setPeriodPayout(address(token), period, 10 ether);
        router.setPeriodPayout(address(token2), period, 10 ether);
        router.setSequencerPercent(sequencer1, epoch, 0.5e18); // 50%

        uint256 token1BalanceBefore = token.balanceOf(sequencer1);
        uint256 token2BalanceBefore = token2.balanceOf(sequencer1);

        // First token withdrawal succeeds
        router.sequencerWithdrawAsset(address(token), sequencer1, epoch);

        // Second token withdrawal also succeeds now (paidOut is per-token)
        router.sequencerWithdrawAsset(address(token2), sequencer1, epoch);

        // Verify both withdrawals worked
        uint256 token1Received = token.balanceOf(sequencer1) - token1BalanceBefore;
        uint256 token2Received = token2.balanceOf(sequencer1) - token2BalanceBefore;

        // paidInEpoch = 10 ether / 10 = 1 ether, amount = 1 * 0.5 = 0.5 ether
        assertEq(token1Received, 0.5 ether, "Should receive token1 share");
        assertEq(token2Received, 0.5 ether, "Should receive token2 share");

        // Verify paidOut is tracked per-token
        assertTrue(router.paidOut(sequencer1, epoch, address(token)), "Token1 marked as paid");
        assertTrue(router.paidOut(sequencer1, epoch, address(token2)), "Token2 marked as paid");
    }

    function test_PaidOut_PreventsDoubleWithdrawPerToken() public {
        // Verify that paidOut still prevents double withdrawal of the same token
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(10 ether);

        uint256 epoch = 0;
        uint256 period = epoch / EPOCHS_PER_PERIOD;
        router.setPeriodPayout(address(token), period, 10 ether);
        router.setSequencerPercent(sequencer1, epoch, 1e18);

        // First withdrawal succeeds
        router.sequencerWithdrawAsset(address(token), sequencer1, epoch);

        // Second withdrawal of SAME token fails
        vm.expectRevert();
        router.sequencerWithdrawAsset(address(token), sequencer1, epoch);
    }

    function test_SequencerWithdraw_Basic() public {
        // Setup
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(10 ether);

        uint256 epoch = 0;
        uint256 period = epoch / EPOCHS_PER_PERIOD;

        // Set period payout (simulating what _record would do)
        router.setPeriodPayout(address(token), period, 10 ether);
        router.setSequencerPercent(sequencer1, epoch, 1e18); // 100%

        uint256 balanceBefore = token.balanceOf(sequencer1);
        router.sequencerWithdrawAsset(address(token), sequencer1, epoch);
        uint256 received = token.balanceOf(sequencer1) - balanceBefore;

        // paidInEpoch = 10 ether / 10 = 1 ether
        // amount = 1 ether * 100% = 1 ether
        assertEq(received, 1 ether, "Sequencer should receive their share");
        assertTrue(router.paidOut(sequencer1, epoch, address(token)), "Should be marked as paid");
    }

    // ==================== YIELD RECORDING TESTS ====================

    function test_RecordYield_Basic() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Add 10 ether yield
        vault.addYield(10 ether);

        // Record yield for period 0
        router.recordYield(address(token), 0);

        assertEq(router.periodPayouts(address(token), 0), 10 ether, "Period payout should be recorded");
        assertEq(router.priorBalances(address(token)), 110 ether, "Prior balance should increase by yield");
    }

    function test_RecordYield_OnlyOncePerPeriod() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        vault.addYield(10 ether);
        router.recordYield(address(token), 0);

        // Add more yield
        vault.addYield(5 ether);

        // Record again - should have no effect
        router.recordYield(address(token), 0);

        // Payout should still be 10 ether (first recording)
        assertEq(router.periodPayouts(address(token), 0), 10 ether, "Should not re-record");
    }

    function test_RecordYield_WithMaxInterest() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        router.setMaxInterest(address(token), 5 ether);
        vault.addYield(10 ether);

        router.recordYield(address(token), 0);

        assertEq(router.periodPayouts(address(token), 0), 5 ether, "Should cap at max interest");
        assertEq(router.priorBalances(address(token)), 105 ether, "Prior balance increases by capped amount");
    }

    function test_RecordYield_UnderOrAtMaxInterest() public {
        // Test branch where maxInterest is set but payment does not exceed cap
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Case 1: Under max - set max to 20, yield is 10
        router.setMaxInterest(address(token), 20 ether);
        vault.addYield(10 ether);
        router.recordYield(address(token), 0);

        assertEq(router.periodPayouts(address(token), 0), 10 ether, "Should not cap when under max");
        assertEq(router.priorBalances(address(token)), 110 ether, "Prior balance increases by full yield");

        // Case 2: Exactly at max - new period with max = yield
        vm.warp(block.timestamp + PERIOD_LENGTH);
        router.setMaxInterest(address(token), 5 ether);
        vault.addYield(5 ether); // Now vault has 115, prior is 110, so yield is 5
        router.recordYield(address(token), 1);

        assertEq(router.periodPayouts(address(token), 1), 5 ether, "Should not cap at exact boundary");
    }

    function test_RecordYield_MaxInterestCarryOver() public {
        // Test that excess yield carries over to next period
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Set max interest to 5 ether
        router.setMaxInterest(address(token), 5 ether);

        // Add 12 ether yield (7 ether excess)
        vault.addYield(12 ether);

        // Record period 0 - capped at 5 ether
        router.recordYield(address(token), 0);
        assertEq(router.periodPayouts(address(token), 0), 5 ether, "Period 0 capped");
        assertEq(router.priorBalances(address(token)), 105 ether, "Prior balance after period 0");

        // Move to next period and record again
        // Vault still has 112 ether, priorBalance is 105, so 7 ether "excess" available
        vm.warp(block.timestamp + PERIOD_LENGTH);
        router.recordYield(address(token), 1);

        // Period 1 should capture the remaining yield (capped again if > 5)
        assertEq(router.periodPayouts(address(token), 1), 5 ether, "Period 1 also capped");
        assertEq(router.priorBalances(address(token)), 110 ether, "Prior balance after period 1");
    }

    // ==================== SET MAX INTEREST FUNCTION TESTS ====================

    function test_SetMaxInterest_Basic() public {
        // Test the new contract function
        router.setMaxInterest(address(token), 50 ether);

        // Verify via the harness getter
        assertEq(router.maxInterest(address(token)), 50 ether, "Max interest should be set");
    }

    function test_SetMaxInterest_OnlyOwner() public {
        vm.prank(user);
        vm.expectRevert();
        router.setMaxInterest(address(token), 50 ether);
    }

    function test_SetMaxInterest_CanUpdate() public {
        router.setMaxInterest(address(token), 50 ether);
        assertEq(router.maxInterest(address(token)), 50 ether, "Initial value");

        router.setMaxInterest(address(token), 100 ether);
        assertEq(router.maxInterest(address(token)), 100 ether, "Updated value");

        // Can also set to zero to clear
        router.setMaxInterest(address(token), 0);
        assertEq(router.maxInterest(address(token)), 0, "Cleared to zero");
    }

    function test_RecordYield_NoYieldNoPayment() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // No yield added
        router.recordYield(address(token), 0);

        assertEq(router.periodPayouts(address(token), 0), 0, "No yield = no payout");
    }

    function test_RecordYield_LossResultsInZeroPayment() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Simulate loss
        vault.simulateLoss(10 ether);

        router.recordYield(address(token), 0);

        // payment = value >= lastBalance ? value - lastBalance : 0
        // 90 >= 100 is false, so payment = 0
        assertEq(router.periodPayouts(address(token), 0), 0, "Loss results in zero payout");
    }

    // ==================== POKE TESTS ====================

    function test_Poke_RecordsAllTrackedSources() public {
        // Add token to tracked sources
        router.addTrackedYieldSource(address(token));

        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(10 ether);

        router.poke();

        uint256 period = router.currentPeriod();
        assertEq(router.periodPayouts(address(token), period), 10 ether, "Should record via poke");
        assertTrue(router.reportedPeriod(period), "Period should be marked as reported");
    }

    function test_Poke_OnlyOncePerPeriod() public {
        router.addTrackedYieldSource(address(token));
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(10 ether);

        router.poke();

        // Add more yield
        vault.addYield(5 ether);

        // Poke again - should not re-record
        router.poke();

        uint256 period = router.currentPeriod();
        assertEq(router.periodPayouts(address(token), period), 10 ether, "Should not re-record");
    }

    function test_TrackedYieldSources_InitializedViaConstructor() public {
        // Create a new router with pre-populated tracked sources
        address[] memory tracked = new address[](2);
        tracked[0] = address(token);
        tracked[1] = address(0x1234);

        YieldRouterHarness routerWithTracked = new YieldRouterHarness(
            PERIOD_LENGTH,
            EPOCHS_PER_PERIOD,
            bridge,
            tracked
        );

        assertEq(routerWithTracked.getTrackedYieldSourcesLength(), 2, "Should have 2 tracked sources");
    }

    function test_ChangeTrackedYieldSources_Basic() public {
        // Initially empty
        assertEq(router.getTrackedYieldSourcesLength(), 0, "No tracked sources initially");

        // Owner can add tracked sources
        address[] memory newTracked = new address[](1);
        newTracked[0] = address(token);
        router.changeTrackedYieldSources(newTracked);

        assertEq(router.getTrackedYieldSourcesLength(), 1, "Should have 1 tracked source");
    }

    function test_ChangeTrackedYieldSources_OnlyOwner() public {
        address[] memory newTracked = new address[](1);
        newTracked[0] = address(token);

        vm.prank(user);
        vm.expectRevert();
        router.changeTrackedYieldSources(newTracked);
    }

    function test_ChangeTrackedYieldSources_CanReplace() public {
        // Add initial sources
        address[] memory initial = new address[](2);
        initial[0] = address(token);
        initial[1] = address(0x1111);
        router.changeTrackedYieldSources(initial);
        assertEq(router.getTrackedYieldSourcesLength(), 2, "Should have 2 sources");

        // Replace with different sources
        address[] memory replacement = new address[](1);
        replacement[0] = address(0x2222);
        router.changeTrackedYieldSources(replacement);
        assertEq(router.getTrackedYieldSourcesLength(), 1, "Should have 1 source after replacement");
    }

    // ==================== REPORT PAYOUT PERCENT TESTS ====================

    function test_ReportPayoutPercent_Basic() public {
        router.testReportPayoutPercent(sequencer1, 0.5e18, 0);

        assertEq(router.sequencerPercents(sequencer1, 0), 0.5e18, "Percent should be recorded");
    }

    function test_ReportPayoutPercent_RejectsOverHundredPercent() public {
        // Percent > 1e18 should be silently ignored
        router.testReportPayoutPercent(sequencer1, 1.5e18, 0);

        assertEq(router.sequencerPercents(sequencer1, 0), 0, "Over 100% should be ignored");
    }

    function test_ReportPayoutPercent_AcceptsExactlyHundredPercent() public {
        router.testReportPayoutPercent(sequencer1, 1e18, 0);

        assertEq(router.sequencerPercents(sequencer1, 0), 1e18, "100% should be accepted");
    }

    // ==================== CHANGE YIELD SOURCE TESTS ====================

    function test_ChangeYieldSource_Basic() public {
        // Setup initial deposit
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Create new vault
        MockERC4626 newVault = new MockERC4626(token);

        // Change source
        router.changeYieldSource(address(token), newVault);

        // Funds should be in new vault
        assertEq(vault.balanceOf(address(router)), 0, "Old vault should be empty");
        assertEq(newVault.balanceOf(address(router)), 100 ether, "New vault should have funds");
        assertEq(address(router.sources(address(token))), address(newVault), "Source should be updated");
    }

    function test_ChangeYieldSource_PreservesYield() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Add yield to old vault
        vault.addYield(10 ether);

        MockERC4626 newVault = new MockERC4626(token);
        router.changeYieldSource(address(token), newVault);

        // Should move full value (100 + 10 = 110)
        assertEq(token.balanceOf(address(newVault)), 110 ether, "New vault should have principal + yield");
    }

    function test_ChangeYieldSource_OnlyOwner() public {
        MockERC4626 newVault = new MockERC4626(token);

        vm.prank(user);
        vm.expectRevert();
        router.changeYieldSource(address(token), newVault);
    }

    function test_ChangeYieldSource_NewSourceWithDeposit() public {
        // Test adding a new source and then depositing to it
        FakeERC20 newToken = new FakeERC20();
        MockERC4626 newVault = new MockERC4626(newToken);

        // Add the new source
        router.changeYieldSource(address(newToken), newVault);

        // Mint tokens to router and deposit
        newToken.mint(address(router), 100 ether);

        // Approve vault from router
        vm.startPrank(address(router));
        newToken.approve(address(newVault), type(uint256).max);
        vm.stopPrank();

        // Now deposit should work
        vm.prank(bridge);
        router.triggerDeposit(address(newToken), 100 ether);

        assertEq(router.priorBalances(address(newToken)), 100 ether, "Deposit should work with new source");
    }

    // ==================== WITHDRAW MANY TESTS ====================

    function test_WithdrawMany_Basic() public {
        router.addTrackedYieldSource(address(token));

        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(10 ether);

        uint256 epoch = 0;
        uint256 period = epoch / EPOCHS_PER_PERIOD;
        router.setPeriodPayout(address(token), period, 10 ether);
        router.setSequencerPercent(sequencer1, epoch, 1e18);

        uint256[] memory epochs = new uint256[](1);
        epochs[0] = epoch;

        uint256 balanceBefore = token.balanceOf(sequencer1);
        router.withdrawMany(sequencer1, epochs);
        uint256 received = token.balanceOf(sequencer1) - balanceBefore;

        assertEq(received, 1 ether, "Should withdraw via withdrawMany");
    }

    // ==================== RECOGNIZE YIELD TESTS ====================

    function test_RecognizeYield_ForUntrackedToken() public {
        // Token not in trackedYieldSources but has a source set
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);
        vault.addYield(10 ether);

        router.recognizeYield(address(token));

        uint256 period = router.currentPeriod();
        assertEq(router.periodPayouts(address(token), period), 10 ether, "Should record yield");
    }

    // ==================== EDGE CASES ====================

    function test_WithdrawMoreThanDeposited() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        // Try to withdraw more than deposited
        vm.expectRevert();
        router.testTriggerWithdraw(address(token), 150 ether, user);
    }

    function test_WithdrawEntireBalance() public {
        token.mint(address(router), 100 ether);
        router.testTriggerDeposit(address(token), 100 ether);

        router.testTriggerWithdraw(address(token), 100 ether, user);

        assertEq(token.balanceOf(user), 100 ether, "User gets full balance");
        assertEq(router.priorBalances(address(token)), 0, "Prior balance is zero");
    }

    // ==================== FUZZ TESTS ====================

    function testFuzz_DepositWithdraw(uint256 depositAmount, uint256 withdrawAmount) public {
        depositAmount = bound(depositAmount, 1, 1000 ether);
        withdrawAmount = bound(withdrawAmount, 1, depositAmount);

        token.mint(address(router), depositAmount);
        router.testTriggerDeposit(address(token), depositAmount);

        router.testTriggerWithdraw(address(token), withdrawAmount, user);

        assertEq(token.balanceOf(user), withdrawAmount, "User receives withdrawal");
        assertEq(router.priorBalances(address(token)), depositAmount - withdrawAmount, "Prior balance updated");
    }

    function testFuzz_YieldRecording(uint256 depositAmount, uint256 yieldAmount) public {
        depositAmount = bound(depositAmount, 1 ether, 1000 ether);
        yieldAmount = bound(yieldAmount, 0, 100 ether);

        token.mint(address(router), depositAmount);
        router.testTriggerDeposit(address(token), depositAmount);

        vault.addYield(yieldAmount);
        router.recordYield(address(token), 0);

        assertEq(router.periodPayouts(address(token), 0), yieldAmount, "Yield recorded correctly");
    }

    function testFuzz_SequencerPercent(uint256 percent) public {
        percent = bound(percent, 0, 2e18); // Include invalid values

        router.testReportPayoutPercent(sequencer1, percent, 0);

        if (percent <= 1e18) {
            assertEq(router.sequencerPercents(sequencer1, 0), percent, "Valid percent recorded");
        } else {
            assertEq(router.sequencerPercents(sequencer1, 0), 0, "Invalid percent ignored");
        }
    }
}
