#!/bin/bash
# Etherscan Contract Verification Script
# Auto-generated by DeployTestnet.s.sol
# Chain ID: 11155111
#
# Prerequisites:
#   export ETHERSCAN_API_KEY=your_api_key
#
# For testnets, you may need to specify the verifier URL:
#   --verifier-url https://api-sepolia.etherscan.io/api
#
set -e

if [ -z "$ETHERSCAN_API_KEY" ]; then
  echo "Error: ETHERSCAN_API_KEY not set"
  exit 1
fi

CHAIN_ID=11155111

echo "Verifying TestnetERC20..."
forge verify-contract \
  0xc536052267Ec6518aa6EAd883373a807DF7A0A59 \
  test/mocks/TestnetERC20.sol:TestnetERC20 \
  --chain-id $CHAIN_ID \
  --constructor-args $(cast abi-encode "constructor(string,string)" "PGP Testnet Token" "tPGP") \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo "Verifying TestnetERC4626..."
forge verify-contract \
  0x2b68F6e432C2F0bef759a1C246c881AcC42184Db \
  test/mocks/TestnetERC4626.sol:TestnetERC4626 \
  --chain-id $CHAIN_ID \
  --constructor-args $(cast abi-encode "constructor(address,string,string)" 0xc536052267Ec6518aa6EAd883373a807DF7A0A59 "PGP Testnet Vault" "vtPGP") \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo "Verifying FakeZK (Transfer Verifier)..."
forge verify-contract \
  0x6782693b0a7b450948bfA101329A2b2929353AD7 \
  test/mocks/FakeZk.sol:FakeZK \
  --chain-id $CHAIN_ID \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo "Verifying FakeZK (Update Verifier)..."
forge verify-contract \
  0x5c69Bdd1e6120a80d08500963b96136544d297e6 \
  test/mocks/FakeZk.sol:FakeZK \
  --chain-id $CHAIN_ID \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo "Verifying TransactionRegistry..."
forge verify-contract \
  0x7774417833e30b77CaF241E7f0dee377cC283D4B \
  src/TransactionRegistry.sol:TransactionRegistry \
  --chain-id $CHAIN_ID \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo "Verifying Entrypoint..."
forge verify-contract \
  0x9874051f38419A3843B01f4Cc8cC40435d663C40 \
  src/Entrypoint.sol:Entrypoint \
  --chain-id $CHAIN_ID \
  --constructor-args $(cast abi-encode "constructor(bytes32,address,address,address,address)" 0x1a6be2423333965b4780e29f3cbe0139e6d50a4d1f5c9ca30f04f2e86d944cf3 0xb516a1861e425b60FC865F6107a1EdC957B0bdd0 0x5c69Bdd1e6120a80d08500963b96136544d297e6 0x6782693b0a7b450948bfA101329A2b2929353AD7 0x7774417833e30b77CaF241E7f0dee377cC283D4B) \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo "Verifying YieldRouter..."
forge verify-contract \
  0xb516a1861e425b60FC865F6107a1EdC957B0bdd0 \
  src/YieldRouter.sol:YieldRouter \
  --chain-id $CHAIN_ID \
  --constructor-args $(cast abi-encode "constructor(uint256,uint256,address,address[])" 86400 48 0x9874051f38419A3843B01f4Cc8cC40435d663C40 "[0xc536052267Ec6518aa6EAd883373a807DF7A0A59]") \
  --etherscan-api-key $ETHERSCAN_API_KEY \
  --watch

echo ""
echo "All contracts verified successfully!"
