// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

// We may have many special purpose versions of these based on the yield integrations.

interface ITransferVerifier {
    // This is the interface used by the autogenerated transfer circuit
    function verifyProof(
        uint256[2] calldata _pA,
        uint256[2][2] calldata _pB,
        uint256[2] calldata _pC,
        uint256[6] calldata _pubSignals
    ) external view returns (bool);
}
